Repository microsoft/vscode, pull requests merged in 2018-07, with the labels that each got.

#49034 WinJS and ES6 Promises
  src/vs/base/common/winjs.base.js
  src/vs/base/test/common/winjs.promise.test.ts
Labels: debt

#45533 Support for updating extensions from CLI
  src/vs/code/node/cliProcessMain.ts
Labels: extensions

#53447 Sign windows uninstaller
  build/gulpfile.hygiene.js
  build/gulpfile.vscode.win32.js
  build/tfs/product-build.yml
  build/tfs/win32/ESRPClient/NuGet.config
  build/tfs/win32/ESRPClient/packages.config
  build/tfs/win32/import-esrp-auth-cert.ps1
  build/tfs/win32/sign.ps1
  build/win32/code.iss
Labels: bug, install-update, windows

#53556 Remove PPromise usage from NSFW IPC
  src/vs/base/common/event.ts
  src/vs/base/parts/ipc/common/ipc.ts
  src/vs/base/parts/ipc/node/ipc.cp.ts
  src/vs/workbench/services/files/node/watcher/nsfw/nsfwWatcherService.ts
  src/vs/workbench/services/files/node/watcher/nsfw/watcher.ts
  src/vs/workbench/services/files/node/watcher/nsfw/watcherIpc.ts
  src/vs/workbench/services/files/node/watcher/nsfw/watcherService.ts
Labels: debt, engineering

#53584 Remove ppromise usage from chokidar
  src/vs/workbench/services/files/node/watcher/unix/chokidarWatcherService.ts
  src/vs/workbench/services/files/node/watcher/unix/test/chockidarWatcherService.test.ts
  src/vs/workbench/services/files/node/watcher/unix/watcher.ts
  src/vs/workbench/services/files/node/watcher/unix/watcherIpc.ts
  src/vs/workbench/services/files/node/watcher/unix/watcherService.ts
Labels: debt, engineering

#46962 Respect ownership on code command installation
  src/vs/workbench/parts/cli/electron-browser/cli.contribution.ts
Labels: mac, os-integration

#50252 [WIP] git: Detect conflict markets in BOTH_ADDED files when staging
  extensions/git/src/commands.ts
Labels: git

#47238 #47041 fixed the scrolling of the editor and cursor after the revert …
  extensions/git/src/commands.ts
Labels: git

#47790 implement push success notification for issue #39039
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
Labels: git

#47819 Commit always using sign off flag setting 47395
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
Labels: git

#47890 add support for ignored repositories list #46763
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/model.ts
Labels: git

#43256 Fixed SCM Badge Issue #42940
  src/vs/base/browser/ui/countBadge/countBadge.css
Labels: scm

#52812 Finalize UriHandler API
  extensions/git/src/protocolHandler.ts
  src/vs/vscode.d.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/electron-browser/mainThreadUrls.ts
  src/vs/workbench/api/node/extHost.api.impl.ts
  src/vs/workbench/api/node/extHost.protocol.ts
  src/vs/workbench/api/node/extHostUrls.ts
Labels: api, api-finalization

#49397 Fixes #48714: Added conversion from local case of the file to git case
  extensions/git/src/git.ts
  extensions/git/src/repository.ts
Labels: git

#53714 Fix for #53710 adopt TS support for checking JSON files
  build/gulpfile.editor.js
  build/gulpfile.mixin.js
  build/gulpfile.vscode.js
  build/gulpfile.vscode.linux.js
  build/gulpfile.vscode.win32.js
  build/lib/builtInExtensions.js
  build/lib/optimize.ts
  build/tsconfig.json
Labels: engineering, vscode-build

#53536 Use events instead of PPromise for search IPC
  src/vs/workbench/services/search/node/fileSearch.ts
  src/vs/workbench/services/search/node/rawSearchService.ts
  src/vs/workbench/services/search/node/ripgrepTextSearch.ts
  src/vs/workbench/services/search/node/search.ts
  src/vs/workbench/services/search/node/searchIpc.ts
  src/vs/workbench/services/search/node/searchService.ts
  src/vs/workbench/services/search/node/textSearch.ts
  src/vs/workbench/services/search/test/node/searchService.test.ts
Labels: debt, search

#53906 Fix bug causing recommendations to sometimes appear in two places
  src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts
  src/vs/workbench/parts/extensions/test/electron-browser/extensionsTipsService.test.ts
Labels: candidate

#53757 Close param hints if you reach out of bounds of list instead of cycling
  src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts
Labels: editor-parameter-hints

#53494 Use HTML headings for viewlet titles.
  src/vs/workbench/browser/media/part.css
  src/vs/workbench/browser/parts/compositePart.ts
  src/vs/workbench/browser/parts/editor/media/titlecontrol.css
  src/vs/workbench/browser/parts/sidebar/media/sidebarpart.css
  src/vs/workbench/browser/parts/views/media/panelviewlet.css
  src/vs/workbench/browser/parts/views/panelViewlet.ts
  src/vs/workbench/parts/debug/electron-browser/callStackView.ts
  src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts
  src/vs/workbench/parts/extensions/electron-browser/media/extensions.css
  src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts
  src/vs/workbench/parts/scm/electron-browser/media/scmViewlet.css
  src/vs/workbench/parts/scm/electron-browser/scmViewlet.ts
  test/smoke/src/areas/workbench/viewlet.ts
Labels: accessibility

#53627 Only fire onDidSelect if user change (fixes: #52632)
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
Labels: dropdown

#53875 Remove PPromise usage from task world
  src/vs/base/node/processes.ts
  src/vs/workbench/parts/tasks/node/processRunnerDetector.ts
  src/vs/workbench/parts/tasks/node/processTaskSystem.ts
Labels: debt, engineering

#53973 Transform languageId of zh-cn,zh-tw to zh-hans,zh-hant when pull tran…
  build/npm/update-localization-extension.js
Labels: i18n

#54224 SelectBox: Implement logic for vertical flip of dropdown: Fixes: #53780
  src/vs/base/browser/ui/selectBox/selectBoxCustom.css
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
Labels: bug, dropdown, settings-editor

#54320 SelectBox: Use offsetWidth to exclude margins. Fixes: #54292
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
Labels: bug, dropdown

#54357 Selectbox Add select/list aria-label option. Partial: #53821 Fixes: #52297
  src/vs/base/browser/ui/actionbar/actionbar.ts
  src/vs/base/browser/ui/selectBox/selectBox.ts
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
  src/vs/base/browser/ui/selectBox/selectBoxNative.ts
Labels: accessibility, dropdown

#54360 SelectBox Clients: Add aria-label value options (ex settingsPreview) Fixes: #53821
  src/vs/workbench/parts/debug/browser/debugActionItems.ts
  src/vs/workbench/parts/debug/electron-browser/breakpointWidget.ts
  src/vs/workbench/parts/output/browser/outputActions.ts
  src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts
Labels: accessibility, dropdown

#54244 Add a reason attribute to filePUT and fileGET
  src/vs/workbench/parts/files/common/editors/fileEditorInput.ts
  src/vs/workbench/services/textfile/common/textFileEditorModel.ts
  src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts
  src/vs/workbench/services/textfile/common/textfiles.ts
  src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts
Labels: telemetry

#54518 Settings: Utilize selectBox.setAriaLabel Related: #53821
  src/vs/workbench/parts/preferences/browser/settingsTree.ts
Labels: accessibility, dropdown, settings-editor

#53616 Down arrow moves focus to extensions list
  src/vs/platform/theme/common/colorRegistry.ts
  src/vs/workbench/parts/extensions/electron-browser/extensionsViewlet.ts
  src/vs/workbench/parts/extensions/electron-browser/extensionsViews.ts
Labels: list

#54662 Support opening folders with other schemes
  src/vs/base/common/labels.ts
  src/vs/base/common/resources.ts
  src/vs/code/electron-main/app.ts
  src/vs/code/electron-main/diagnostics.ts
  src/vs/code/electron-main/launch.ts
  src/vs/code/electron-main/menubar.ts
  src/vs/code/electron-main/menus.ts
  src/vs/code/electron-main/window.ts
  src/vs/code/electron-main/windows.ts
  src/vs/code/node/windowsFinder.ts
  src/vs/code/test/node/windowsFinder.test.ts
  src/vs/editor/standalone/browser/simpleServices.ts
  src/vs/platform/backup/common/backup.ts
  src/vs/platform/backup/electron-main/backupMainService.ts
  src/vs/platform/backup/test/electron-main/backupMainService.test.ts
  src/vs/platform/environment/common/environment.ts
  src/vs/platform/environment/node/argv.ts
  src/vs/platform/history/common/history.ts
  src/vs/platform/history/electron-main/historyMainService.ts
  src/vs/platform/windows/common/windows.ts
  src/vs/platform/windows/common/windowsIpc.ts
  src/vs/platform/windows/electron-browser/windowService.ts
  src/vs/platform/windows/electron-main/windows.ts
  src/vs/platform/windows/electron-main/windowsService.ts
  src/vs/platform/workspace/common/workspace.ts
  src/vs/platform/workspaces/common/workspaces.ts
  src/vs/workbench/api/electron-browser/mainThreadWorkspace.ts
  src/vs/workbench/api/node/apiCommands.ts
  src/vs/workbench/api/node/extHostWorkspace.ts
  src/vs/workbench/browser/actions/workspaceActions.ts
  src/vs/workbench/browser/dnd.ts
  src/vs/workbench/browser/parts/menubar/menubarPart.ts
  src/vs/workbench/electron-browser/actions.ts
  src/vs/workbench/electron-browser/commands.ts
  src/vs/workbench/electron-browser/main.ts
  src/vs/workbench/electron-browser/window.ts
  src/vs/workbench/parts/extensions/electron-browser/extensionTipsService.ts
  src/vs/workbench/parts/files/electron-browser/fileActions.ts
  src/vs/workbench/parts/files/electron-browser/fileCommands.ts
  src/vs/workbench/parts/preferences/common/preferencesContribution.ts
  src/vs/workbench/parts/stats/node/workspaceStats.ts
  src/vs/workbench/parts/welcome/page/electron-browser/welcomePage.ts
  src/vs/workbench/services/configuration/node/configurationService.ts
  src/vs/workbench/services/configuration/test/electron-browser/configurationService.test.ts
  src/vs/workbench/services/files/node/watcher/win32/watcherService.ts
  src/vs/workbench/services/keybinding/test/electron-browser/keybindingEditing.test.ts
  src/vs/workbench/services/textfile/common/textFileEditorModel.ts
  src/vs/workbench/services/workspace/node/workspaceEditingService.ts
  src/vs/workbench/test/workbenchTestServices.ts
Labels: workbench-history

#53871 Parts splash
  package.json
  src/vs/workbench/electron-browser/bootstrap/index.js
  src/vs/workbench/electron-browser/main.ts
  src/vs/workbench/electron-browser/shell.ts
  yarn.lock
Labels: perf-startup

#53503 Fixes #53372
  src/vs/workbench/electron-browser/main.contribution.ts
  src/vs/workbench/parts/preferences/browser/preferencesActions.ts
  src/vs/workbench/parts/preferences/electron-browser/preferences.contribution.ts
  src/vs/workbench/services/preferences/browser/preferencesService.ts
  src/vs/workbench/services/preferences/common/preferences.ts
Labels: config

#55054 Add underscores and asterisks to surrounding pairs
  extensions/markdown-basics/language-configuration.json
Labels: markdown
