Repository microsoft/vscode, pull requests merged in 2018-04, with the labels that each got.

#47052 #46860 make git delete popup modal
  extensions/git/src/commands.ts
Labels: git

#47044 SelectBox: Add bounds checking on selected option. Addresses: #43475, #44309
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
  src/vs/base/browser/ui/selectBox/selectBoxNative.ts
Labels: dropdown

#47445 SelectBox: Bounds check/adjust selected option (Fix2). Addresses: #43475, #44309
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
  src/vs/base/browser/ui/selectBox/selectBoxNative.ts
Labels: dropdown

#47226 add monaco-typecheck tasks
  .travis.yml
  appveyor.yml
  build/gulpfile.editor.js
  build/lib/reporter.js
  build/lib/reporter.ts
  gulpfile.js
Labels: engineering

#47678 Allow extensions to access all terminals
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/electron-browser/mainThreadTerminalService.ts
  src/vs/workbench/api/node/extHost.api.impl.ts
  src/vs/workbench/api/node/extHost.protocol.ts
  src/vs/workbench/api/node/extHostTerminalService.ts
  src/vs/workbench/parts/terminal/common/terminal.ts
  src/vs/workbench/parts/terminal/common/terminalService.ts
  src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts
  src/vs/workbench/parts/terminal/electron-browser/terminalService.ts
Labels: api-proposal

#42789 Fix typo
  i18n/cht/src/vs/workbench/parts/emmet/electron-browser/emmet.contribution.i18n.json
Labels: i18n

#48091 Selectbox: Remove workbench css ref, add min bottom margin. Fixes: #44915
  src/vs/base/browser/ui/selectBox/selectBox.ts
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
Labels: dropdown

#48037 Dynamic composite bar
  src/vs/workbench/browser/composite.ts
  src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
  src/vs/workbench/browser/parts/compositePart.ts
  src/vs/workbench/browser/parts/compositebar/compositeBar.ts
  src/vs/workbench/browser/parts/panel/panelPart.ts
  src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts
  src/vs/workbench/parts/extensions/electron-browser/extensions.contribution.ts
  src/vs/workbench/parts/scm/electron-browser/scm.contribution.ts
  src/vs/workbench/parts/search/electron-browser/search.contribution.ts
  src/vs/workbench/services/viewlet/browser/viewlet.ts
  src/vs/workbench/services/viewlet/browser/viewletService.ts
Labels: workbench-layout

#48400 Fix bad localize usage of localize
  extensions/npm/src/main.ts
  extensions/npm/src/npmView.ts
  extensions/npm/src/tasks.ts
Labels: important
