Repository microsoft/vscode, pull requests merged in 2019-04, with the labels that each got.

#71531 Show notification when default formatter is gone
  src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts
Labels: candidate

#71601 Report snap on telemetry, issue reporter, about menu
  src/vs/code/electron-browser/issue/issueReporterMain.ts
  src/vs/platform/telemetry/node/commonProperties.ts
  src/vs/platform/windows/electron-main/windowsService.ts
Labels: candidate

#71397 Expose uriScheme through vscode.env
  src/vs/vscode.d.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/node/extHost.api.impl.ts
Labels: api, api-finalization

#71633 Update distro
  package.json
Labels: candidate

#71981 Fix #71707
  src/vs/editor/contrib/format/format.ts
  src/vs/workbench/api/browser/mainThreadSaveParticipant.ts
  src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts
Labels: formatting

#71999 Take mooncake upload out of build critical path
  build/azure-pipelines/common/publish.ts
  build/azure-pipelines/common/sync-mooncake.ts
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/linux/product-build-linux.yml
  build/azure-pipelines/linux/snap-build-linux.yml
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/sync-mooncake.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: candidate

#72026 Expose vscode.openIssueReporter command that allows passing an extensionId to open the reporter with
  src/vs/code/electron-browser/issue/issueReporterMain.ts
  src/vs/platform/issue/common/issue.ts
  src/vs/workbench/api/common/apiCommands.ts
  src/vs/workbench/api/common/extHostApiCommands.ts
  src/vs/workbench/contrib/issue/electron-browser/issue.contribution.ts
  src/vs/workbench/contrib/issue/electron-browser/issueActions.ts
Labels: api

#73054 Update statusBarItem.remoteBackground
  src/vs/workbench/common/theme.ts
Labels: candidate

#73010 Comments API Finalization
  src/vs/editor/common/modes.ts
  src/vs/vscode.d.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/browser/mainThreadComments.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostComments.ts
  src/vs/workbench/api/node/extHost.api.impl.ts
  src/vs/workbench/contrib/comments/browser/commentService.ts
  src/vs/workbench/contrib/comments/browser/commentThreadWidget.ts
  src/vs/workbench/contrib/comments/browser/commentsEditorContribution.ts
Labels: api-finalization
