Repository microsoft/vscode, pull requests merged in 2019-03, with the labels that each got.

#69716 avoid extensionTestsLocationURI.fsPath as it normalizes path
  src/vs/workbench/api/node/extHostExtensionService.ts
Labels: candidate

#68653 Add workspace name variable for snippets #68261
  src/vs/editor/contrib/snippet/snippetSession.ts
  src/vs/editor/contrib/snippet/snippetVariables.ts
  src/vs/editor/contrib/snippet/test/snippetVariables.test.ts
Labels: feature-request, snippets

#69701 Make an error message easier to understand
  build/gulpfile.hygiene.js
Labels: engineering

#60426 git: Open File command fix on clean tree
  extensions/git/src/commands.ts
Labels: git

#67155 Fixing Intelisense verbosity with screen readers
  src/vs/editor/contrib/suggest/suggestController.ts
  src/vs/editor/contrib/suggest/suggestWidget.ts
Labels: accessibility

#69864 Fix #69862
  extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts
  src/vs/workbench/api/electron-browser/mainThreadWorkspace.ts
  src/vs/workbench/contrib/search/common/queryBuilder.ts
  src/vs/workbench/contrib/search/test/common/queryBuilder.test.ts
Labels: candidate

#69863 Fix #69840
  extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts
  src/vs/workbench/api/electron-browser/mainThreadWorkspace.ts
Labels: candidate

#69877 Fix #69875
  src/vs/workbench/api/electron-browser/mainThreadWorkspace.ts
  src/vs/workbench/api/node/extHost.protocol.ts
  src/vs/workbench/api/node/extHostWorkspace.ts
Labels: candidate

#69570 Show a quickpick for changing display language
  src/vs/workbench/contrib/localizations/browser/localizationsActions.ts
Labels: i18n

#69861 Cleanup: Remove duplicate configuration from outline.contribution.ts
  src/vs/workbench/contrib/outline/browser/outline.contribution.ts
Labels: breadcrumbs, debt

#69979 Removed Snap related code from updateService.linux.ts
  src/vs/platform/update/electron-main/updateService.linux.ts
  src/vs/platform/update/electron-main/updateService.snap.ts
Labels: linux, snap

#60573 Fixes Git Clone Problem with Spaces
  extensions/git/src/git.ts
Labels: git

#60640 Support for remote management in git
  src/tsconfig.strictNullChecks.json
  src/vs/base/common/event.ts
  src/vs/workbench/api/electron-browser/mainThreadDebugService.ts
Labels: git

#70188 Selectbox: Remove explicit select role (Electron 2 workaround)
  src/vs/base/browser/ui/selectBox/selectBoxCustom.ts
  src/vs/base/browser/ui/selectBox/selectBoxNative.ts
Labels: debt, dropdown

#70213 Open vscode://file/<path> in vscode is broken. Fixes #69998
  src/vs/platform/windows/electron-main/windowsService.ts
Labels: candidate, workbench-os-integration

#70345 fixes #70022
  src/vs/base/browser/ui/menu/menubar.ts
Labels: candidate

#70402 Use yarn artifact caching build tasks
  build/azure-pipelines/darwin/continuous-build-darwin.yml
  build/azure-pipelines/linux/continuous-build-linux.yml
  build/azure-pipelines/win32/continuous-build-win32.yml
Labels: engineering

#70686 feat(coffeescript): Add `.iced` extension
  extensions/coffeescript/package.json
Labels: grammar

#70717 Support string in TerminalOptions.shellArgs
  src/vs/vscode.d.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/electron-browser/mainThreadTerminalService.ts
  src/vs/workbench/api/node/extHostTerminalService.ts
Labels: api, api-finalization, api-proposal

#70867 Remove some dead code in base/parts/tree/
  src/vs/base/parts/quickopen/browser/quickOpenModel.ts
  src/vs/base/parts/tree/browser/tree.ts
  src/vs/base/parts/tree/browser/treeImpl.ts
  src/vs/base/parts/tree/browser/treeModel.ts
  src/vs/workbench/browser/actions.ts
Labels: tree

#70884 Snapcraft update. Fixes #63194 Fixes #57019
  resources/linux/snap/electron-launch
  resources/linux/snap/snapcraft.yaml
Labels: install-update, linux, snap

#70521 Fix custom viewlet not being shown when its cached views are not active on registration
  src/vs/workbench/browser/parts/activitybar/activitybarPart.ts
Labels: explorer-custom

#71292 Stop the Settings tree from jittering
  src/vs/base/browser/ui/list/list.ts
  src/vs/base/browser/ui/list/listView.ts
  src/vs/base/browser/ui/tree/abstractTree.ts
  src/vs/workbench/contrib/preferences/browser/settingsTree.ts
Labels: settings-editor
