Repository microsoft/vscode, pull requests merged in 2019-10, with the labels that each got.

#81297 Fix character escaping in snippet transformation
  src/vs/editor/contrib/snippet/snippetParser.ts
  src/vs/editor/contrib/snippet/test/snippetParser.test.ts
Labels: snippets

#81923 Adopt icon font in problems and peek error
  src/vs/editor/contrib/gotoError/gotoErrorWidget.ts
  src/vs/editor/contrib/referenceSearch/media/peekViewWidget.css
  src/vs/platform/severityIcon/common/severityIcon.ts
  src/vs/platform/theme/common/colorRegistry.ts
  src/vs/workbench/common/theme.ts
  src/vs/workbench/contrib/extensions/browser/extensionsViews.ts
  src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
  src/vs/workbench/contrib/markers/browser/media/markers.css
Labels: icons-product

#82092 blah
  package.json
Labels: candidate

#82111 Change scm default from tree to list
  src/vs/workbench/contrib/scm/browser/scm.contribution.ts
Labels: candidate

#82046 Use SIGUSR1 for automatic extension profiling
  scripts/test-integration.bat
  scripts/test-integration.sh
  src/vs/platform/environment/common/environment.ts
  src/vs/platform/environment/node/argv.ts
  src/vs/workbench/contrib/debug/node/debugAdapter.ts
  src/vs/workbench/contrib/extensions/electron-browser/extensionProfileService.ts
  src/vs/workbench/contrib/extensions/electron-browser/extensionsAutoProfiler.ts
  src/vs/workbench/contrib/extensions/electron-browser/runtimeExtensionsEditor.ts
  src/vs/workbench/services/extensions/browser/webWorkerExtensionHostStarter.ts
  src/vs/workbench/services/extensions/common/abstractExtensionService.ts
  src/vs/workbench/services/extensions/common/extensionHostProcessManager.ts
  src/vs/workbench/services/extensions/common/extensions.ts
  src/vs/workbench/services/extensions/common/remoteExtensionHostClient.ts
  src/vs/workbench/services/extensions/electron-browser/extensionHost.ts
  src/vs/workbench/services/extensions/electron-browser/extensionService.ts
  src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts
Labels: debt

#82171 Notifications icon polish
  src/vs/base/browser/ui/codiconLabel/codicon/codicon.css
  src/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf
  src/vs/workbench/browser/parts/notifications/media/notificationsList.css
  src/vs/workbench/browser/parts/notifications/notificationsActions.ts
  src/vs/workbench/browser/parts/notifications/notificationsCenter.ts
Labels: icons-product, workbench-notifications

#82341 Fix #82203 for recovery
  src/vs/base/common/resourceTree.ts
  src/vs/workbench/contrib/scm/browser/repositoryPanel.ts
Labels: candidate, scm

#82342 Fixes #82257 for recovery
  src/vs/workbench/contrib/scm/browser/media/scmViewlet.css
Labels: candidate

#82223 Fixes #82212
  src/vs/code/electron-main/app.ts
Labels: candidate

#82150 Fixes #82149
  src/vs/base/common/resourceTree.ts
Labels: bug, candidate, scm

#82349 Fixed the problem of overwriting many characters in suggestion
  src/vs/editor/contrib/suggest/suggestController.ts
Labels: suggest

#82274 Show dirty state icon when workbench.editor.tabCloseButton is off
  src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css
Labels: candidate, icons-product, workbench-tabs

#82301 adopt font window icon controls
  src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css
  src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
Labels: titlebar

#82503 Recovery fix for #82252
  package.json
Labels: candidate

#82505 Fixes #82359 for recovery build
  src/vs/workbench/services/extensions/node/extensionPoints.ts
Labels: candidate

#82517 Update Octicon mapping in quick pick
  src/vs/base/browser/ui/codiconLabel/codicon/codicon.css
Labels: candidate, icons-product

#82531 fix resource rewrite before host available
  src/vs/base/common/network.ts
Labels: candidate

#82377 php - fix custom tags appearing invalid
  extensions/php/build/update-grammar.js
  extensions/php/syntaxes/html.tmLanguage.json
  extensions/php/test/colorize-fixtures/issue-76997.php
  extensions/php/test/colorize-results/issue-76997_php.json
Labels: php

#82539 Windows Edition in Workspace Stats
  src/vs/workbench/contrib/stats/electron-browser/workspaceStats.ts
Labels: telemetry

#82553 Update Octicon mapping in quick pick v2
  src/vs/base/browser/ui/codiconLabel/codicon/codicon.css
  src/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf
Labels: candidate

#82209 #75938 - Added in setting for diff gutter visibility
  src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts
  src/vs/workbench/contrib/scm/browser/scm.contribution.ts
Labels: scm

#82486 Add chromium command line args
  src/vs/platform/environment/common/environment.ts
  src/vs/platform/environment/node/argv.ts
Labels: workbench-cli

#66522 When resolving a merge conflict allow accepting the default message
  extensions/git/src/commands.ts
  extensions/git/src/git.ts
  extensions/git/src/repository.ts
Labels: git

#71341 Show git clone progress bar and percentage complete
  extensions/git/src/commands.ts
  extensions/git/src/git.ts
Labels: git

#71525 Confirm "Undo last commit" if its a merge commit
  extensions/git/src/commands.ts
Labels: git

#72615 allow `Git: fetch` command to show password prompt
  extensions/git/src/askpass-main.ts
Labels: git

#80965 Fix scrolling behavior in menu while zoomed in
  src/vs/base/browser/ui/actionbar/actionbar.ts
  src/vs/base/browser/ui/menu/menu.ts
  src/vs/base/browser/ui/menu/menubar.ts
Labels: menus

#82787 Show breakpoints in overview ruler
  src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts
  src/vs/workbench/contrib/debug/browser/debug.contribution.ts
  src/vs/workbench/contrib/debug/common/debug.ts
Labels: debug

#82038 Fix git repository not detected if root folder ends in [space]
  extensions/git/src/git.ts
Labels: git

#82992 CI Builds with GitHub Actions
  .github/workflows/ci.yml
Labels: engineering

#83153 Use the editor font size for the breakpoint widget
  src/vs/workbench/contrib/debug/browser/breakpointWidget.ts
  src/vs/workbench/contrib/debug/browser/media/breakpointWidget.css
Labels: debug

#77260 fix: error when filling in the HTTP proxy address in IPv6 format
  src/vs/platform/request/common/request.ts
Labels: proxy

#83060 Rework Uri.parse and Uri.toString
  src/vs/base/common/strings.ts
  src/vs/base/common/uri.ts
  src/vs/base/test/node/uri.test.ts
  src/vs/editor/browser/services/openerService.ts
  src/vs/monaco.d.ts
  src/vs/vscode.d.ts
  src/vs/workbench/api/common/extHostTypeConverters.ts
  src/vs/workbench/contrib/debug/test/common/debugSource.test.ts
  src/vs/workbench/contrib/webview/common/portMapping.ts
  src/vs/workbench/electron-browser/window.ts
  src/vs/workbench/services/search/test/node/ripgrepTextSearchEngine.test.ts
  src/vs/workbench/test/electron-browser/api/extHostTypeConverter.test.ts
  src/vs/workbench/test/electron-browser/api/extHostTypes.test.ts
Labels: uri

#74345 added deleteTag
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/api/git.d.ts
  extensions/git/src/commands.ts
  extensions/git/src/git.ts
  extensions/git/src/repository.ts
Labels: git

#79566 Focus correct SCM repo when restoring editors
  src/vs/workbench/contrib/scm/browser/scmActivity.ts
Labels: scm

#83262 Adopt icon font in debug viewlet
  src/vs/workbench/contrib/debug/browser/callStackView.ts
  src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts
  src/vs/workbench/contrib/debug/browser/debugActions.ts
  src/vs/workbench/contrib/debug/browser/debugToolBar.ts
  src/vs/workbench/contrib/debug/browser/debugViewlet.ts
  src/vs/workbench/contrib/debug/browser/media/add-dark.svg
  src/vs/workbench/contrib/debug/browser/media/add-hc.svg
  src/vs/workbench/contrib/debug/browser/media/add-light.svg
  src/vs/workbench/contrib/debug/browser/media/close-all-dark.svg
  src/vs/workbench/contrib/debug/browser/media/close-all-hc.svg
  src/vs/workbench/contrib/debug/browser/media/close-all-light.svg
  src/vs/workbench/contrib/debug/browser/media/configure-dark.svg
  src/vs/workbench/contrib/debug/browser/media/configure-hc.svg
  src/vs/workbench/contrib/debug/browser/media/configure-light.svg
  src/vs/workbench/contrib/debug/browser/media/console-dark.svg
  src/vs/workbench/contrib/debug/browser/media/console-hc.svg
  src/vs/workbench/contrib/debug/browser/media/console-light.svg
  src/vs/workbench/contrib/debug/browser/media/continue-white.svg
  src/vs/workbench/contrib/debug/browser/media/debugViewlet.css
  src/vs/workbench/contrib/debug/browser/media/disconnect-white.svg
  src/vs/workbench/contrib/debug/browser/media/pause-white.svg
  src/vs/workbench/contrib/debug/browser/media/restart-white.svg
  src/vs/workbench/contrib/debug/browser/media/start-dark.svg
  src/vs/workbench/contrib/debug/browser/media/start-hc.svg
  src/vs/workbench/contrib/debug/browser/media/start-light.svg
  src/vs/workbench/contrib/debug/browser/media/step-into-white.svg
  src/vs/workbench/contrib/debug/browser/media/step-out-white.svg
  src/vs/workbench/contrib/debug/browser/media/step-over-white.svg
  src/vs/workbench/contrib/debug/browser/media/stop-white.svg
  src/vs/workbench/contrib/debug/browser/media/toggle-breakpoints-dark.svg
  src/vs/workbench/contrib/debug/browser/media/toggle-breakpoints-hc.svg
  src/vs/workbench/contrib/debug/browser/media/toggle-breakpoints-light.svg
  src/vs/workbench/contrib/debug/browser/variablesView.ts
  src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts
Labels: icons-product

#83760 Fixes #82208
  src/vs/base/browser/ui/tree/abstractTree.ts
  src/vs/platform/list/browser/listService.ts
  src/vs/workbench/contrib/outline/browser/outlinePanel.ts
Labels: tree
