Repository microsoft/vscode, pull requests merged in 2020-07, with the labels that each got.

#101677 Improve text of SCM count badge settings
  src/vs/workbench/contrib/scm/browser/scm.contribution.ts
Labels: scm

#101796 Joao/release/1.47/101688
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: candidate, scm

#101687 Update notebook output width
  src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
Labels: candidate

#101825 Update debug icon for action bar
  src/vs/base/browser/ui/codicons/codicon/codicon.ttf
  src/vs/base/common/codicons.ts
Labels: candidate, icons-product

#101862 debug: update js-debug to 1.47.3
  product.json
Labels: candidate, debug

#101869 Fix color token for notebook focused cell bg
  extensions/theme-defaults/themes/light_defaults.json
Labels: candidate, notebook

#101875 debug: update table visualizer version
  product.json
Labels: candidate

#101966 Add navigation role to settings-toc-wrapper
  src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts
Labels: accessibility

#102362 fix #102148
  src/vs/platform/workspaces/common/workspaces.ts
Labels: candidate

#102392 debug: bump js-debug to 1.47.5 for recovery
  product.json
Labels: candidate

#102327 debug: use previous node debug for auto attach in the the July release
  extensions/debug-auto-launch/src/extension.ts
Labels: candidate, debug

#102479 Release fixes #102358
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: candidate, scm

#102524 chore: cherry pick commits from robo/msrc_58478
  package.json
Labels: candidate

#102968 Make editor on type bg color themeable
  src/vs/editor/contrib/rename/media/onTypeRename.css
  src/vs/editor/contrib/rename/onTypeRename.ts
Labels: themes

#102966 chore: bump distro
  package.json
Labels: candidate

#102949 Sandboxed issue reporter
  build/gulpfile.vscode.js
  src/vs/code/buildfile.js
  src/vs/code/electron-sandbox/issue/issueReporter.html
  src/vs/code/electron-sandbox/issue/issueReporter.js
  src/vs/code/electron-sandbox/issue/issueReporterMain.ts
  src/vs/code/electron-sandbox/issue/issueReporterModel.ts
  src/vs/code/electron-sandbox/issue/issueReporterPage.ts
  src/vs/code/electron-sandbox/issue/media/issueReporter.css
  src/vs/code/electron-sandbox/issue/test/testReporterModel.test.ts
  src/vs/platform/issue/electron-main/issueMainService.ts
Labels: sandbox
