Repository microsoft/vscode, pull requests merged in 2020-05, with the labels that each got.

#96807 chore: bump electron@7.2.4
  .yarnrc
  cgmanifest.json
  package.json
  src/vs/platform/menubar/electron-main/menubar.ts
  yarn.lock
Labels: candidate

#96873 Sync state should be scoped per workspace in Web
  src/vs/workbench/services/environment/browser/environmentService.ts
Labels: settings-sync

#96820 editor groups - resolve #96725
  src/vs/workbench/common/editor/editorGroup.ts
  src/vs/workbench/test/browser/parts/editor/editorGroups.test.ts
Labels: candidate

#96810 Text buffer in CellTextModel and hook up with Working Copy Service
  extensions/vscode-notebook-tests/src/notebook.test.ts
  src/vs/editor/common/model.ts
  src/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.ts
  src/vs/workbench/api/browser/mainThreadNotebook.ts
  src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts
  src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
  src/vs/workbench/contrib/notebook/browser/notebookBrowser.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditor.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditorInput.ts
  src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts
  src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/codeCell.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/markdownCell.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/baseCellViewModel.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/cellEdit.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/codeCellViewModel.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/markdownCellViewModel.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.ts
  src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts
  src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts
  src/vs/workbench/contrib/notebook/common/notebookCommon.ts
  src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts
  src/vs/workbench/contrib/notebook/common/notebookService.ts
  src/vs/workbench/contrib/notebook/test/notebookTextModel.test.ts
  src/vs/workbench/contrib/notebook/test/notebookViewModel.test.ts
  src/vs/workbench/contrib/notebook/test/testNotebookEditor.ts
Labels: notebook

#97023 Apply scroll area to hover content, not status bar
  src/vs/workbench/contrib/terminal/browser/widgets/hoverWidget.ts
Labels: candidate

#97072 statusBar: focusNext and focusPrevious
  src/vs/workbench/browser/parts/statusbar/statusbarPart.ts
  src/vs/workbench/services/statusbar/common/statusbar.ts
Labels: accessibility

#97057 List: re-anounce element when focus did not change on typing
  src/vs/base/browser/ui/list/listWidget.ts
Labels: accessibility, list, under-discussion

#97487 Fix proxy auth dialog for release
  src/vs/code/electron-browser/proxy/auth.html
Labels: candidate

#97604 Disable askpass, terminal and github auth when git is disabled
  extensions/git/src/askpass.ts
  extensions/git/src/github.ts
  extensions/git/src/terminal.ts
Labels: candidate

#88308 Add ability to change screencast keyboard font size
  src/vs/workbench/browser/actions/developerActions.ts
  src/vs/workbench/browser/actions/media/actions.css
Labels: screencast-mode

#97849 add breakpointMargin property to cell metadata
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts
  src/vs/workbench/contrib/notebook/common/notebookCommon.ts
Labels: feature-request

#97825 vscode api: introduce accessibilityInformation
  src/vs/base/browser/ui/list/listView.ts
  src/vs/platform/accessibility/common/accessibility.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/browser/mainThreadStatusBar.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostStatusBar.ts
  src/vs/workbench/api/common/extHostTimeline.ts
  src/vs/workbench/api/common/extHostTreeViews.ts
  src/vs/workbench/browser/parts/views/treeView.ts
  src/vs/workbench/common/views.ts
  src/vs/workbench/contrib/timeline/browser/timelinePane.ts
  src/vs/workbench/contrib/timeline/common/timeline.ts
Labels: accessibility, api

#97912 editor: introduce anchor selection
  src/vs/editor/contrib/anchorSelect/anchorSelect.css
  src/vs/editor/contrib/anchorSelect/anchorSelect.ts
  src/vs/editor/editor.all.ts
Labels: accessibility

#98236 editor: conoslidte computing of editor aria labels
  src/vs/workbench/browser/parts/editor/editor.ts
  src/vs/workbench/browser/parts/editor/tabsTitleControl.ts
  src/vs/workbench/browser/parts/editor/textDiffEditor.ts
  src/vs/workbench/browser/parts/editor/textEditor.ts
  src/vs/workbench/browser/parts/editor/textResourceEditor.ts
  src/vs/workbench/common/editor.ts
  src/vs/workbench/contrib/files/browser/editors/textFileEditor.ts
  src/vs/workbench/services/untitled/common/untitledTextEditorInput.ts
Labels: accessibility

#98235 SCM - Add support for filteting on the file path
  src/vs/workbench/browser/labels.ts
  src/vs/workbench/contrib/scm/browser/repositoryPane.ts
Labels: scm

#93184 Containerfile support
  build/lib/electron.ts
  build/win32/code.iss
  extensions/docker/package.json
  extensions/search-result/syntaxes/generateTMLanguage.js
Labels: workbench-os-integration

#98607 differentiate notebook moving to new group and splitting
  src/vs/workbench/browser/parts/editor/editor.ts
  src/vs/workbench/browser/parts/editor/editorGroupView.ts
  src/vs/workbench/contrib/customEditor/browser/customEditors.ts
  src/vs/workbench/contrib/files/browser/fileActions.ts
  src/vs/workbench/contrib/files/common/openWith.ts
  src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditor.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditorInput.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts
  src/vs/workbench/services/editor/browser/editorService.ts
  src/vs/workbench/services/editor/common/editorGroupsService.ts
  src/vs/workbench/services/editor/common/editorService.ts
  src/vs/workbench/services/editor/test/browser/editorGroupsService.test.ts
Labels: notebook
