Repository microsoft/vscode, pull requests merged in 2020-12, with the labels that each got.

#112009 Revert "build: create asset should still try to add asset"
  build/azure-pipelines/common/createAsset.ts
Labels: candidate

#112008 Mitigate #109728
  src/vs/workbench/contrib/update/browser/update.ts
Labels: candidate

#112049 Suggest a different description for Get Started switch
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.contribution.ts
Labels: polish

#112026 Use the right deb repository for Linux ARM builds
  build/gulpfile.vscode.linux.js
  resources/linux/debian/postinst.template
Labels: candidate, linux

#112054 debug: bump js-debug
  product.json
Labels: candidate, debug

#112019 fix: Param helper hover getting cut off at bottom
  src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts
Labels: editor-parameter-hints

#111787 fix: disable shm usage in container builds
  scripts/test-integration.sh
  scripts/test.sh
Labels: engineering

#112226 Fix linux deb repo pointer
  resources/linux/debian/postinst.template
Labels: engineering, linux

#112245 chore: fix run-on values for snap build
  build/gulpfile.vscode.linux.js
Labels: candidate

#112224 polyfill nested workers for safari
  src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts
  src/vs/workbench/services/extensions/common/polyfillNestedWorker.protocol.ts
  src/vs/workbench/services/extensions/worker/extensionHostWorker.ts
  src/vs/workbench/services/extensions/worker/httpWebWorkerExtensionHostIframe.html
  src/vs/workbench/services/extensions/worker/httpsWebWorkerExtensionHostIframe.html
  src/vs/workbench/services/extensions/worker/polyfillNestedWorker.ts
Labels: feature-request, safari

#112206 Updates tsec to latest version using TS4.1.2
  package.json
  yarn.lock
Labels: engineering

#112431 Fix notebook status bar icon colors
  src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts
Labels: candidate, notebook

#111222 add file decorations to editor titles (tab and no tab)
  src/vs/base/browser/ui/iconLabel/iconlabel.css
  src/vs/workbench/browser/parts/editor/media/titlecontrol.css
  src/vs/workbench/browser/parts/editor/noTabsTitleControl.ts
  src/vs/workbench/browser/parts/editor/tabsTitleControl.ts
  src/vs/workbench/browser/workbench.contribution.ts
  src/vs/workbench/common/editor.ts
Labels: feature-request, file-decorations

#112670 fix: hover link encode unnecessarily
  src/vs/editor/contrib/links/links.ts
Labels: editor-hover

#113536 No need to use containers for compilation and hygiene jobs
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/product-compile.yml
  build/azure-pipelines/product-hygiene.yml
Labels: engineering
