Repository microsoft/vscode, pull requests merged in 2021-09, with the labels that each got.

#132020 Bump distro
  package.json
Labels: candidate

#132290 only run language detection on plaintext files
  src/vs/workbench/services/textfile/common/textFileEditorModel.ts
Labels: candidate

#132534 Remove colorized bracket pair for plain text files
  src/vs/editor/common/modes/modesRegistry.ts
Labels: bracket-pair-colorization

#132530 Workspace trust - Add telemetry for workspace trust dialogs
  src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts
Labels: workspace-trust

#132512 Update to latest seti-ui icon theme
  extensions/theme-seti/cgmanifest.json
  extensions/theme-seti/icons/seti.woff
  extensions/theme-seti/icons/vs-seti-icon-theme.json
Labels: feature-request, themes, verification-needed

#132870 Fix launching Pseudoterminal-based and local terminals in remote workspaces before the connection is established
  src/vs/workbench/api/browser/mainThreadTerminalService.ts
  src/vs/workbench/contrib/terminal/browser/terminalService.ts
Labels: candidate

#133019 Add notebook output border color token
  src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/webviewThemeMapping.ts
Labels: notebook, notebook-output

#132996 Intial work to add error to telemetry setting
  src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts
  src/vs/code/electron-main/app.ts
  src/vs/code/node/cliProcessMain.ts
  src/vs/platform/extensionManagement/common/extensionGalleryService.ts
  src/vs/platform/extensionManagement/test/common/extensionGalleryService.test.ts
  src/vs/platform/telemetry/common/telemetry.ts
  src/vs/platform/telemetry/common/telemetryService.ts
  src/vs/platform/telemetry/common/telemetryUtils.ts
  src/vs/platform/telemetry/test/browser/telemetryService.test.ts
  src/vs/workbench/api/browser/mainThreadTelemetry.ts
  src/vs/workbench/contrib/logs/common/logs.contribution.ts
  src/vs/workbench/contrib/remote/electron-sandbox/remote.contribution.ts
  src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts
  src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
  src/vs/workbench/services/extensionResourceLoader/browser/extensionResourceLoaderService.ts
  src/vs/workbench/services/telemetry/electron-sandbox/telemetryService.ts
Labels: telemetry

#131213 Add prototype of mac open command
  src/vs/base/node/watcher.ts
  src/vs/code/node/cli.ts
Labels: macos, engineering

#133177 Don't run language detection if a default language is set
  src/vs/workbench/common/editor/textEditorModel.ts
  src/vs/workbench/services/untitled/common/untitledTextEditorModel.ts
Labels: candidate

#133465 Move appenders to be better controlled by services
  src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts
  src/vs/code/electron-main/app.ts
  src/vs/code/node/cliProcessMain.ts
  src/vs/editor/standalone/browser/simpleServices.ts
  src/vs/platform/extensionManagement/common/extensionGalleryService.ts
  src/vs/platform/telemetry/common/telemetry.ts
  src/vs/platform/telemetry/common/telemetryService.ts
  src/vs/platform/telemetry/common/telemetryUtils.ts
  src/vs/platform/telemetry/node/customEndpointTelemetryService.ts
  src/vs/platform/telemetry/test/browser/telemetryService.test.ts
  src/vs/workbench/api/browser/mainThreadTelemetry.ts
  src/vs/workbench/contrib/debug/browser/debugSession.ts
  src/vs/workbench/contrib/logs/common/logs.contribution.ts
  src/vs/workbench/contrib/remote/electron-sandbox/remote.contribution.ts
  src/vs/workbench/contrib/tags/electron-sandbox/workspaceTags.ts
  src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts
  src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts
  src/vs/workbench/services/experiment/common/experimentService.ts
  src/vs/workbench/services/extensionResourceLoader/browser/extensionResourceLoaderService.ts
  src/vs/workbench/services/telemetry/browser/telemetryService.ts
  src/vs/workbench/services/telemetry/electron-sandbox/telemetryService.ts
  src/vs/workbench/test/electron-browser/textsearch.perf.integrationTest.ts
Labels: telemetry

#133494 TAS treatment for language recommendation prompt
  src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts
Labels: extension-recommendations

#133651 Make Help menu entries more useful for exploration
  src/vs/workbench/browser/actions/helpActions.ts
  src/vs/workbench/contrib/quickaccess/browser/quickAccess.contribution.ts
  src/vs/workbench/contrib/update/browser/update.contribution.ts
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.contribution.ts
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStartedInput.ts
  src/vs/workbench/contrib/welcome/gettingStarted/common/gettingStartedContent.ts
  src/vs/workbench/contrib/welcome/walkThrough/browser/editor/editorWalkThrough.ts
  src/vs/workbench/contrib/welcome/walkThrough/browser/walkThrough.contribution.ts
Labels: polish, menus

#134161 Walkthrough items for web
  src/vs/workbench/contrib/welcome/gettingStarted/common/gettingStartedContent.ts
Labels: web
