Repository microsoft/vscode, pull requests merged in 2021-03, with the labels that each got.

#117774 Factor in workspace trust when switching versions
  extensions/typescript-language-features/package.json
  extensions/typescript-language-features/src/tsServer/versionManager.ts
Labels: workspace-trust

#117842 Update seti-ui icon theme
  extensions/theme-seti/README.md
  extensions/theme-seti/build/update-icon-theme.js
  extensions/theme-seti/cgmanifest.json
  extensions/theme-seti/icons/seti.woff
  extensions/theme-seti/icons/vs-seti-icon-theme.json
Labels: themes

#117925 Fixes #117924
  src/vs/platform/theme/common/colorRegistry.ts
Labels: candidate

#117759 Fixing emmet issue where incorrect abbreviation is displayed in an html file
  extensions/emmet/src/defaultCompletionProvider.ts
Labels: bug, emmet

#117974 Update vscode.d.ts
  src/vs/vscode.d.ts
Labels: debug

#115351 fix #62531 add negative text filtering to Problems
  src/vs/workbench/contrib/markers/browser/markersFilterOptions.ts
  src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
Labels: error-list

#118167 debug: update js-debug
  product.json
Labels: candidate

#118250 Don't assume uncompleted category exists
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts
Labels: candidate

#118219 allow debug textmate in sandbox
  src/vs/workbench/contrib/codeEditor/electron-browser/codeEditor.contribution.ts
  src/vs/workbench/contrib/codeEditor/electron-sandbox/codeEditor.contribution.ts
  src/vs/workbench/contrib/codeEditor/electron-sandbox/startDebugTextMate.ts
  src/vs/workbench/workbench.desktop.main.ts
Labels: sandbox

#118425 fixes #118214
  extensions/theme-abyss/themes/abyss-color-theme.json
  extensions/theme-kimbie-dark/themes/kimbie-dark-color-theme.json
  extensions/theme-monokai-dimmed/themes/dimmed-monokai-color-theme.json
  extensions/theme-monokai/themes/monokai-color-theme.json
  extensions/theme-quietlight/themes/quietlight-color-theme.json
  extensions/theme-red/themes/Red-color-theme.json
  extensions/theme-solarized-dark/themes/solarized-dark-color-theme.json
  extensions/theme-solarized-light/themes/solarized-light-color-theme.json
  extensions/theme-tomorrow-night-blue/themes/tomorrow-night-blue-color-theme.json
  src/vs/platform/theme/common/colorRegistry.ts
Labels: candidate

#118269 Add Julia indentation rules
  extensions/julia/language-configuration.json
Labels: languages-basic

#118437 Don't force kill ptys on Windows on window exit
  src/vs/platform/terminal/node/terminalProcess.ts
  src/vs/workbench/contrib/terminal/browser/terminalService.ts
Labels: candidate

#118265 debug: update js-debug
  product.json
Labels: candidate, debug

#118438 Recover on pty host reconnect
  src/vs/platform/terminal/common/terminal.ts
  src/vs/platform/terminal/electron-browser/localPtyService.ts
  src/vs/workbench/contrib/terminal/browser/terminal.ts
  src/vs/workbench/contrib/terminal/browser/terminalInstance.ts
  src/vs/workbench/contrib/terminal/browser/terminalInstanceService.ts
  src/vs/workbench/contrib/terminal/browser/terminalProcessManager.ts
  src/vs/workbench/contrib/terminal/browser/terminalService.ts
  src/vs/workbench/contrib/terminal/browser/terminalTab.ts
  src/vs/workbench/contrib/terminal/browser/terminalView.ts
  src/vs/workbench/contrib/terminal/common/terminal.ts
  src/vs/workbench/contrib/terminal/electron-browser/terminalInstanceService.ts
Labels: candidate

#117099 fix #117093 update Filter on Type indicator after 'list.toggleFilterOnType' command
  src/vs/base/browser/ui/tree/abstractTree.ts
Labels: tree-widget

#118956 fs - go back to previous realpath version & increment version
  package.json
  src/vs/base/node/extpath.ts
Labels: candidate

#118212 Add "Copy As..." core submenu to editor context and Edit titlebar menu
  src/vs/editor/contrib/clipboard/clipboard.ts
  src/vs/platform/actions/common/actions.ts
  src/vs/workbench/api/common/menusExtensionPoint.ts
  src/vs/workbench/browser/parts/titlebar/menubarControl.ts
  src/vs/workbench/electron-sandbox/parts/titlebar/menubarControl.ts
Labels: menus

#118826 Do no install repo on Raspberry Pi OS
  resources/linux/debian/postinst.template
Labels: linux

#119017 Workspace trust changes
  extensions/typescript-language-features/package.json
  extensions/vscode-api-tests/package.json
  src/vs/platform/extensions/common/extensions.ts
  src/vs/platform/workspace/common/workspaceTrust.ts
  src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts
  src/vs/workbench/contrib/workspace/browser/workspaceTrustEditor.ts
  src/vs/workbench/services/extensionManagement/browser/extensionEnablementService.ts
  src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts
  src/vs/workbench/services/extensions/common/extensions.ts
  src/vs/workbench/services/workspaces/common/workspaceTrust.ts
Labels: workspace-trust

#119292 Getting started polish
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.css
  src/vs/workbench/contrib/welcome/gettingStarted/browser/gettingStarted.ts
Labels: getting-started

#119658 Workspace trust - API feedback
  src/vs/platform/workspace/common/workspaceTrust.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/browser/mainThreadWorkspace.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostWorkspace.ts
  src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts
  src/vs/workbench/services/workspaces/common/workspaceTrust.ts
  src/vs/workbench/services/workspaces/test/common/testWorkspaceTrustService.ts
Labels: workspace-trust

#119980 debug: fix stop on entry not working after launch.json change
  src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts
Labels: candidate

#119483 Workspace trust - multi-window improvements
  src/vs/workbench/services/workspaces/common/workspaceTrust.ts
Labels: workspace-trust

#119979 iPad OS ctrl + c in terminal
  src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts
Labels: candidate

#119967 allow terminal profiles w source to have args
  src/vs/workbench/contrib/terminal/browser/terminalService.ts
  src/vs/workbench/contrib/terminal/common/terminal.ts
  src/vs/workbench/contrib/terminal/node/terminalProfiles.ts
  src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts
Labels: candidate

#119977 High-contrast images for getting started
  src/vs/workbench/contrib/welcome/gettingStarted/common/gettingStartedContent.ts
  src/vs/workbench/contrib/welcome/gettingStarted/common/media/dark/commandPalette.png
  src/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/commandPalette.png
  src/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/extensions.png
  src/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/settingsSync.png
  src/vs/workbench/contrib/welcome/gettingStarted/common/media/hc/terminal.png
  src/vs/workbench/contrib/welcome/gettingStarted/common/media/light/commandPalette.png
Labels: candidate

#119972 Remove RemoteHub from desktop stable
  product.json
Labels: candidate

#119987 Finalize setting name: displayDetectedWslProfiles -> useWslProfiles
  src/vs/workbench/contrib/terminal/browser/terminalService.ts
  src/vs/workbench/contrib/terminal/common/terminal.ts
  src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts
  src/vs/workbench/contrib/terminal/node/terminalProfiles.ts
  src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts
Labels: candidate

#117268 Enable terminal event batching from ptyHost
  src/vs/platform/terminal/common/terminalDataBuffering.ts
  src/vs/platform/terminal/node/ptyService.ts
Labels: candidate

#119981 [Getting Started] new file => new untitled file rather than explorer's new file
  src/vs/workbench/contrib/welcome/gettingStarted/common/gettingStartedContent.ts
Labels: candidate

#119990 Fix test compilation
  src/vs/workbench/contrib/terminal/test/node/terminalProfiles.test.ts
Labels: candidate

#120005 Remove code that is not needed
  extensions/vscode-api-tests/package.json
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/services/extensions/common/extensions.ts
Labels: workspace-trust

#120028 Workspace trust - extension enablement
  src/vs/platform/extensions/common/extensions.ts
  src/vs/workbench/contrib/workspace/browser/workspaceTrustEditor.ts
  src/vs/workbench/services/extensionManagement/browser/extensionEnablementService.ts
  src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts
Labels: workspace-trust

#119983 Respect viewtype for reopen with in notebooks
  src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts
  src/vs/workbench/contrib/notebook/common/notebookEditorModelResolverService.ts
  src/vs/workbench/contrib/notebook/common/notebookService.ts
Labels: candidate

#120080 Fixes #120066
  src/vs/editor/contrib/clipboard/clipboard.ts
Labels: candidate

#119817 Show current DataBreakpoint access type in "Breakpoints" view (#119588)
  src/vs/workbench/contrib/debug/browser/breakpointsView.ts
  src/vs/workbench/contrib/debug/browser/media/debugViewlet.css
Labels: debug

#120109 Finalizes extension object to ExtensionContext
  src/vs/vscode.d.ts
  src/vs/vscode.proposed.d.ts
Labels: candidate

#120107 semantic highlighting no longer works for js/jsx files
  extensions/typescript-language-features/package.json
  extensions/typescript-language-features/yarn.lock
Labels: candidate, typescript

#120086 fix(notebook): redo cell creation does not re-select the cell
  extensions/vscode-api-tests/src/singlefolder-tests/notebook.test.ts
  src/vs/workbench/contrib/notebook/browser/contrib/coreActions.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.ts
Labels: debt, notebook

#120059 allow authority in wt
  src/vs/platform/workspace/common/workspaceTrust.ts
  src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts
  src/vs/workbench/contrib/workspace/browser/workspaceTrustEditor.css
  src/vs/workbench/contrib/workspace/browser/workspaceTrustEditor.ts
  src/vs/workbench/contrib/workspace/browser/workspaceTrustTree.ts
  src/vs/workbench/services/workspaces/common/workspaceTrust.ts
Labels: workspace-trust

#120128 handle error when wsl is not installed
  src/vs/workbench/contrib/terminal/node/terminalProfiles.ts
Labels: candidate

#120168 Joao/release/1.55/120062
  src/vs/base/browser/ui/table/tableWidget.ts
Labels: candidate

#120161 Update markdown-it
  extensions/extension-editing/package.json
  extensions/extension-editing/yarn.lock
Labels: engineering
