Repository microsoft/vscode, pull requests merged in 2021-02, with the labels that each got.

#115513 Fix Search Mode setting does not open editors unless search view is visible
  src/vs/workbench/contrib/search/browser/search.contribution.ts
Labels: candidate

#115514 Register a separate action for opening search editor from view
  src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts
Labels: candidate

#115387 Improving performance of tree traversal on getViewState function
  src/vs/base/browser/ui/tree/asyncDataTree.ts
Labels: tree

#115446 typeahead: line wrap improvements
  src/vs/workbench/contrib/terminal/browser/terminalTypeAheadAddon.ts
  src/vs/workbench/contrib/terminal/test/browser/terminalTypeahead.test.ts
Labels: integrated-terminal-local-echo

#109412 notebooks: add generic colors for renderers
  src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/webviewThemeMapping.ts
  src/vs/workbench/contrib/webview/browser/baseWebviewElement.ts
  src/vs/workbench/contrib/webview/browser/themeing.ts
  src/vs/workbench/contrib/webview/browser/webview.ts
Labels: notebook

#115558 Fix keybinding for Search view missing from view and sidebar
  src/vs/workbench/contrib/search/browser/search.contribution.ts
Labels: candidate

#115573 debug: mark terminal as free when the associated debug session ends
  src/vs/workbench/api/browser/mainThreadDebugService.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostDebugService.ts
  src/vs/workbench/api/node/extHostDebugService.ts
  src/vs/workbench/contrib/debug/browser/debugAdapterManager.ts
  src/vs/workbench/contrib/debug/browser/debugSession.ts
  src/vs/workbench/contrib/debug/browser/rawDebugSession.ts
  src/vs/workbench/contrib/debug/common/debug.ts
  src/vs/workbench/contrib/debug/common/debugger.ts
  src/vs/workbench/contrib/debug/test/browser/repl.test.ts
  src/vs/workbench/contrib/debug/test/browser/telemetry.test.ts
Labels: debug

#115636 Azure DevOps - Add global variable for VSCODE_QUALITY
  build/azure-pipelines/product-build.yml
Labels: engineering

#115530 Hide API implementation proxies, add tests to check for "proxy leakage"
  extensions/vscode-api-tests/src/singlefolder-tests/commands.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/configuration.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/debug.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/editor.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/env.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/languages.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/quickInput.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/rpc.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/terminal.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/types.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/webview.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/window.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/workspace.event.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/workspace.fs.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/workspace.tasks.test.ts
  extensions/vscode-api-tests/src/singlefolder-tests/workspace.test.ts
  extensions/vscode-api-tests/src/utils.ts
  src/vs/workbench/api/browser/mainThreadEditor.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostClipboard.ts
  src/vs/workbench/api/common/extHostCodeInsets.ts
  src/vs/workbench/api/common/extHostDebugService.ts
  src/vs/workbench/api/common/extHostDocumentsAndEditors.ts
  src/vs/workbench/api/common/extHostFileSystemConsumer.ts
  src/vs/workbench/api/common/extHostStoragePaths.ts
  src/vs/workbench/api/common/extHostTask.ts
  src/vs/workbench/api/common/extHostTerminalService.ts
  src/vs/workbench/api/common/extHostTextEditor.ts
  src/vs/workbench/api/common/extHostTextEditors.ts
  src/vs/workbench/api/node/extHostTerminalService.ts
  src/vs/workbench/services/extensions/common/rpcProtocol.ts
  src/vs/workbench/test/browser/api/extHostTextEditor.test.ts
Labels: debt

#115673 Azure DevOps - Add global variable for VSCODE_QUALITY (#115636)
  build/azure-pipelines/product-build.yml
Labels: engineering

#114182 Fix: add alwaysConsumeMouseWheel for list
  src/vs/base/browser/ui/list/listView.ts
  src/vs/base/browser/ui/list/listWidget.ts
  src/vs/editor/contrib/suggest/suggestWidget.ts
Labels: list

#115309 Add Julia grammar
  extensions/julia/.vscodeignore
  extensions/julia/cgmanifest.json
  extensions/julia/language-configuration.json
  extensions/julia/package.json
  extensions/julia/package.nls.json
  extensions/julia/syntaxes/julia.tmLanguage.json
  extensions/search-result/syntaxes/generateTMLanguage.js
  extensions/search-result/syntaxes/searchResult.tmLanguage.json
  extensions/vscode-colorize-tests/test/colorize-fixtures/test.jl
  extensions/vscode-colorize-tests/test/colorize-results/test_jl.json
Labels: languages-basic

#115772 Update Codicons to add 'git-pull-request-create'
  src/vs/base/browser/ui/codicons/codicon/codicon.ttf
  src/vs/base/common/codicons.ts
Labels: candidate

#115789 fix notebook document runstate
  src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts
Labels: candidate

#116256 fix: CreateFile ERROR_FILE_NOT_FOUND from crashpad handler
  src/vs/code/electron-main/window.ts
Labels: candidate

#116354 Workspace trust refactoring
  src/vs/platform/workspace/common/workspaceTrust.ts
  src/vs/workbench/browser/actions/workspaceActions.ts
  src/vs/workbench/contrib/experiments/test/electron-browser/experimentService.test.ts
  src/vs/workbench/contrib/extensions/test/electron-browser/extensionsActions.test.ts
  src/vs/workbench/contrib/update/browser/update.ts
  src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts
  src/vs/workbench/contrib/workspace/common/workspaceTrustFileSystemProvider.ts
  src/vs/workbench/services/extensionManagement/test/browser/extensionEnablementService.test.ts
  src/vs/workbench/services/workspaces/common/workspaceTrust.ts
  src/vs/workbench/services/workspaces/test/common/testWorkspaceTrustService.ts
  src/vs/workbench/test/browser/workbenchTestServices.ts
Labels: workspace-trust

#115817 notebook outputs api
  extensions/vscode-notebook-tests/src/notebook.test.ts
  extensions/vscode-notebook-tests/src/notebookSmokeTestMain.ts
  extensions/vscode-notebook-tests/src/notebookTestMain.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/browser/mainThreadNotebook.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostNotebook.ts
  src/vs/workbench/api/common/extHostNotebookDocument.ts
  src/vs/workbench/api/common/extHostNotebookEditor.ts
  src/vs/workbench/api/common/extHostTypeConverters.ts
  src/vs/workbench/api/common/extHostTypes.ts
  src/vs/workbench/contrib/notebook/browser/diff/diffComponents.ts
  src/vs/workbench/contrib/notebook/browser/diff/diffElementOutputs.ts
  src/vs/workbench/contrib/notebook/browser/diff/diffElementViewModel.ts
  src/vs/workbench/contrib/notebook/browser/diff/notebookDiff.css
  src/vs/workbench/contrib/notebook/browser/diff/notebookDiffEditorBrowser.ts
  src/vs/workbench/contrib/notebook/browser/diff/notebookTextDiffEditor.ts
  src/vs/workbench/contrib/notebook/browser/media/notebook.css
  src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
  src/vs/workbench/contrib/notebook/browser/notebookBrowser.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts
  src/vs/workbench/contrib/notebook/browser/notebookRegistry.ts
  src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts
  src/vs/workbench/contrib/notebook/browser/view/output/outputRenderer.ts
  src/vs/workbench/contrib/notebook/browser/view/output/transforms/errorTransform.ts
  src/vs/workbench/contrib/notebook/browser/view/output/transforms/richTransform.ts
  src/vs/workbench/contrib/notebook/browser/view/output/transforms/streamTransform.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts
  src/vs/workbench/contrib/notebook/browser/view/renderers/cellOutput.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/cellEdit.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/cellOutputViewModel.ts
  src/vs/workbench/contrib/notebook/browser/viewModel/notebookViewModel.ts
  src/vs/workbench/contrib/notebook/common/model/notebookCellOutputTextModel.ts
  src/vs/workbench/contrib/notebook/common/model/notebookCellTextModel.ts
  src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts
  src/vs/workbench/contrib/notebook/common/notebookCommon.ts
  src/vs/workbench/contrib/notebook/common/notebookService.ts
  src/vs/workbench/contrib/notebook/common/services/notebookSimpleWorker.ts
  src/vs/workbench/contrib/notebook/common/services/notebookWorkerServiceImpl.ts
  src/vs/workbench/contrib/notebook/test/notebookTextModel.test.ts
  src/vs/workbench/contrib/notebook/test/testNotebookEditor.ts
Labels: notebook

#116560 Update node-fetch from 2.6.0 to 2.6.1
  extensions/github-authentication/package.json
  extensions/github-authentication/yarn.lock
  extensions/github/yarn.lock
  extensions/microsoft-authentication/package.json
  extensions/microsoft-authentication/yarn.lock
Labels: engineering

#116912 Emmet: add css.color.short setting
  extensions/emmet/package.json
  extensions/emmet/package.nls.json
Labels: emmet, feature-request, hackathon

#115582 Update smoke test README
  test/smoke/README.md
Labels: debt, feature-request

#116938 Azure DevOps build task to download built-in extension details
  build/azure-pipelines/product-compile.yml
  build/lib/builtInExtensions.ts
  build/lib/builtInExtensionsCG.js
  build/lib/builtInExtensionsCG.ts
  build/package.json
  build/yarn.lock
  package.json
  product.json
Labels: engineering

#116986 powershell 7 not showing in 32bit vscode on 64bit Windows
  src/vs/base/node/powershell.ts
  src/vs/base/test/node/powershell.test.ts
Labels: integrated-terminal

#117230 remove colon from git host in askpass arguments
  extensions/git/src/askpass-main.ts
Labels: git

#117241 Removed optional message, and added modal parameter
  src/vs/platform/workspace/common/workspaceTrust.ts
  src/vs/vscode.proposed.d.ts
  src/vs/workbench/api/browser/mainThreadWorkspace.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostWorkspace.ts
  src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts
  src/vs/workbench/contrib/workspace/browser/workspace.contribution.ts
  src/vs/workbench/services/extensionManagement/browser/extensionEnablementService.ts
  src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts
  src/vs/workbench/services/workspaces/common/workspaceTrust.ts
Labels: workspace-trust

#116856 Remove editorOpenWith
  src/vs/platform/editor/common/editor.ts
  src/vs/workbench/api/browser/mainThreadEditors.ts
  src/vs/workbench/api/browser/mainThreadNotebook.ts
  src/vs/workbench/api/common/extHostTypeConverters.ts
  src/vs/workbench/browser/editor.ts
  src/vs/workbench/browser/parts/editor/editorActions.ts
  src/vs/workbench/browser/parts/editor/editorCommands.ts
  src/vs/workbench/browser/parts/editor/editorDropTarget.ts
  src/vs/workbench/common/editor.ts
  src/vs/workbench/contrib/customEditor/browser/customEditors.ts
  src/vs/workbench/contrib/customEditor/common/contributedCustomEditors.ts
  src/vs/workbench/contrib/files/browser/editors/binaryFileEditor.ts
  src/vs/workbench/contrib/files/browser/explorerViewlet.ts
  src/vs/workbench/contrib/files/browser/fileActions.ts
  src/vs/workbench/contrib/files/browser/fileCommands.ts
  src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts
  src/vs/workbench/contrib/notebook/browser/notebookEditor.ts
  src/vs/workbench/contrib/notebook/browser/notebookServiceImpl.ts
  src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts
  src/vs/workbench/contrib/welcome/walkThrough/browser/editor/editorWalkThrough.ts
  src/vs/workbench/services/editor/browser/editorService.ts
  src/vs/workbench/services/editor/common/editorOpenWith.ts
  src/vs/workbench/services/editor/common/editorService.ts
  src/vs/workbench/services/editor/test/browser/editorService.test.ts
  src/vs/workbench/test/browser/workbenchTestServices.ts
Labels: debt
