Repository microsoft/vscode, pull requests merged in 2021-12, with the labels that each got.

#138287 Improve remote connection
  src/vs/base/parts/ipc/common/ipc.net.ts
  src/vs/base/parts/ipc/test/node/ipc.net.test.ts
  src/vs/platform/remote/common/remoteAgentConnection.ts
  src/vs/platform/remote/node/nodeSocketFactory.ts
  src/vs/server/remoteExtensionHostAgentServer.ts
  src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts
Labels: remote-connection

#138302 Update editor configuration only after extensions are registered
  src/vs/workbench/browser/parts/editor/editorConfiguration.ts
Labels: perf, perf-startup

#138293 SCM - Introduce another open changes command got editor/command palette
  extensions/git/package.json
  extensions/git/src/commands.ts
Labels: scm

#138512 make sure theme is loaded when restoring it
  src/vs/workbench/services/themes/browser/workbenchThemeService.ts
Labels: bug, themes

#137672 Make typings on `showInformationMessage`, `showWarningMessage`, `showErrorMessage` strict with items as strings
  src/vscode-dts/vscode.d.ts
Labels: under-discussion, api-finalization

#138645 Correct the description of `screencastMode.keyboardShortcutsFormat` setting (#138644)
  src/vs/workbench/browser/actions/developerActions.ts
Labels: screencast-mode

#138662 Codicon registry cleanup
  src/vs/base/browser/ui/codicons/codicon/codicon.css
  src/vs/base/common/codicons.ts
  src/vs/editor/common/modes.ts
  src/vs/editor/contrib/quickAccess/gotoSymbolQuickAccess.ts
  src/vs/editor/contrib/suggest/suggestMemory.ts
  src/vs/editor/contrib/suggest/suggestWidgetRenderer.ts
  src/vs/platform/terminal/common/terminalPlatformConfiguration.ts
  src/vs/platform/theme/browser/iconsStyleSheet.ts
  src/vs/platform/theme/common/iconRegistry.ts
  src/vs/platform/theme/common/themeService.ts
  src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
  src/vs/workbench/contrib/callHierarchy/browser/callHierarchyTree.ts
  src/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsTree.ts
  src/vs/workbench/contrib/debug/browser/repl.ts
  src/vs/workbench/contrib/search/browser/symbolsQuickAccess.ts
  src/vs/workbench/contrib/terminal/browser/terminalIcon.ts
  src/vs/workbench/contrib/terminal/browser/terminalInstance.ts
  src/vs/workbench/contrib/terminal/browser/terminalProfileQuickpick.ts
  src/vs/workbench/contrib/terminal/browser/terminalProfileResolverService.ts
  src/vs/workbench/contrib/terminal/browser/terminalService.ts
  src/vs/workbench/contrib/typeHierarchy/browser/typeHierarchyTree.ts
  src/vs/workbench/contrib/welcome/banner/browser/welcomeBanner.contribution.ts
  src/vs/workbench/services/decorations/browser/decorationsService.ts
Labels: debt

#139070 Go back to using `setImmediate` for background tokenization
  src/vs/base/common/platform.ts
  src/vs/editor/common/model/textModelTokens.ts
Labels: candidate

#138796 Candidate for #138110
  src/vs/base/browser/ui/menu/menu.ts
Labels: candidate

#138782 Ensure `forceNewSession` overload gets picked first (#138685)
  src/vscode-dts/vscode.d.ts
Labels: candidate

#139209 Fix typo in watcher.ts
  src/vs/platform/files/common/watcher.ts
Labels: triage-needed

#139498 SCM - do not leak RPC proxy
  extensions/vscode-api-tests/src/singlefolder-tests/rpc.test.ts
  src/vs/workbench/api/common/extHostCommands.ts
  src/vs/workbench/api/common/extHostSCM.ts
Labels: debt, scm

#139657 Workaround Safari clipboard.writeText behavior
  src/vs/editor/standalone/browser/standaloneServices.ts
  src/vs/platform/clipboard/browser/clipboardService.ts
  src/vs/workbench/contrib/notebook/test/browser/testNotebookEditor.ts
  src/vs/workbench/services/clipboard/browser/clipboardService.ts
Labels: triage-needed
