Repository microsoft/vscode, pull requests merged in 2022-05, with the labels that each got.

#148458 Fixes #148447 (#148456)
  src/bootstrap.js
Labels: candidate

#148047 Remove SCMRepository instances from context service
  src/vs/base/common/iterator.ts
  src/vs/workbench/contrib/scm/browser/activity.ts
  src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts
  src/vs/workbench/contrib/scm/browser/scm.contribution.ts
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
  src/vs/workbench/contrib/scm/common/scm.ts
  src/vs/workbench/contrib/scm/common/scmService.ts
Labels: scm

#148438 fix: close `create fork` message will create fork
  extensions/github/src/pushErrorHandler.ts
Labels: github

#148567 Don't cache keytar until we know it works
  src/vs/platform/credentials/common/credentialsMainService.ts
  src/vs/platform/credentials/electron-main/credentialsMainService.ts
Labels: candidate

#147947 Adopt WCO for Windows
  src/vs/platform/native/common/native.ts
  src/vs/platform/native/electron-main/nativeHostMainService.ts
  src/vs/platform/windows/electron-main/window.ts
  src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css
  src/vs/workbench/browser/parts/titlebar/menubarControl.ts
  src/vs/workbench/browser/parts/titlebar/titlebarPart.ts
  src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts
  src/vs/workbench/services/contextmenu/electron-sandbox/contextmenuService.ts
  src/vs/workbench/test/electron-browser/workbenchTestServices.ts
Labels: windows, titlebar, windows 11

#148563 Ensure tab api properly states unpin status.
  src/vs/workbench/common/editor/editorGroupModel.ts
  src/vs/workbench/test/browser/parts/editor/editorGroupModel.test.ts
Labels: candidate

#148564 run global bash profile file
  src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
Labels: candidate

#148562 fix 148561
  src/vs/workbench/services/textMate/common/TMGrammars.ts
Labels: candidate

#148591 debug: bump js-debug companion
  product.json
Labels: candidate

#148573 Respect passed in `autoStart` in desktop case
  src/vs/workbench/services/extensions/browser/extensionService.ts
  src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts
  src/vs/workbench/services/extensions/electron-browser/extensionService.ts
Labels: candidate

#148594 testing: hide ANSI color codes in test peeks
  src/vs/workbench/contrib/testing/browser/testingOutputPeek.ts
  src/vs/workbench/contrib/testing/browser/theme.ts
  src/vs/workbench/contrib/testing/common/testResult.ts
  src/vs/workbench/contrib/testing/common/testTypes.ts
  src/vs/workbench/contrib/testing/common/testingContentProvider.ts
Labels: testing

#148663 Default to only show language detection hints in text editors
  src/vs/workbench/browser/workbench.contribution.ts
  src/vs/workbench/contrib/languageDetection/browser/languageDetection.contribution.ts
  src/vs/workbench/contrib/notebook/browser/contrib/cellStatusBar/statusBarProviders.ts
  src/vs/workbench/services/languageDetection/common/languageDetectionWorkerService.ts
Labels: candidate

#148688 Update Dockerfile fixture/result
  extensions/vscode-colorize-tests/test/colorize-fixtures/Dockerfile
  extensions/vscode-colorize-tests/test/colorize-results/Dockerfile.json
Labels: engineering

#148819 Have forceNewSession behave like createIfNone if no sessions are present
  src/vs/workbench/api/browser/mainThreadAuthentication.ts
  src/vs/workbench/api/test/browser/extHostAuthentication.test.ts
  src/vscode-dts/vscode.d.ts
Labels: authentication

#148752 add owner and comment to a telemetry event
  extensions/github-authentication/src/github.ts
  extensions/microsoft-authentication/src/extension.ts
  src/vs/workbench/api/browser/mainThreadAuthentication.ts
  src/vs/workbench/services/languageDetection/common/languageDetectionWorkerService.ts
Labels: telemetry

#148961 Finalize InputBoxMessageSeverity API
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHostQuickOpen.ts
  src/vs/workbench/services/extensions/common/extensionsApiProposals.ts
  src/vscode-dts/vscode.d.ts
  src/vscode-dts/vscode.proposed.inputBoxSeverity.d.ts
Labels: api

#148785 Added extension search text length to telemetry
  src/vs/platform/extensionManagement/common/extensionGalleryService.ts
Labels: extensions

#148632 Generate ADMX/ADML policy declaration files from static analysis
  build/.cachesalt
  build/.gitignore
  build/azure-pipelines/win32/product-build-win32.yml
  build/gulpfile.vscode.js
  build/lib/policies.js
  build/lib/policies.ts
  build/lib/tsb/builder.js
  build/lib/tsb/builder.ts
  build/lib/watch/.gitignore
  build/lib/watch/package.json
  build/lib/watch/yarn.lock
  build/npm/dirs.js
  build/npm/postinstall.js
  build/package.json
  build/yarn.lock
  resources/win32/policies/Code.admx
  resources/win32/policies/en-US/Code.adml
  src/vs/platform/configuration/common/configurationRegistry.ts
  src/vs/platform/update/common/update.config.contribution.ts
Labels: config

#149069 Git - branch prefix + random name generation
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
  extensions/git/yarn.lock
Labels: git

#149093 Fix #137330
  src/vs/workbench/contrib/scm/browser/activity.ts
Labels: scm

#149241 Enable random branch creation
  .vscode/settings.json
Labels: git

#149171 Engineering - create pull request pipeline
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/linux/product-build-linux-client.yml
  build/azure-pipelines/linux/product-build-linux-server.yml
  build/azure-pipelines/product-build-pr.yml
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/product-compile.yml
  build/azure-pipelines/win32/product-build-win32.yml
  extensions/vscode-api-tests/src/singlefolder-tests/extensions.test.ts
  test/automation/src/application.ts
  test/smoke/src/areas/statusbar/statusbar.test.ts
  test/smoke/src/main.ts
Labels: engineering

#149278 Switch web endpoint back to vortex.
  src/vs/workbench/services/telemetry/browser/telemetryService.ts
Labels: candidate, telemetry, web

#149150 Add "Open Containing Folder" etc to file context menu in Git SCM view
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
Labels: scm

#149437 Add branch protection settings
  .vscode/settings.json
Labels: git

#149469 Git - Add trace level telemetry to repository discovery
  extensions/git/src/main.ts
  extensions/git/src/model.ts
Labels: git

#149485 Update foreground color of extension list item descriptions
  src/vs/workbench/contrib/extensions/browser/media/extension.css
Labels: themes

#149691 Engineering - switch agent pools
  build/azure-pipelines/product-build-pr.yml
Labels: engineering

#149700 Engineering - Run PR pipeline for the main branch
  build/azure-pipelines/product-build-pr.yml
Labels: engineering

#149698 Engineering - Exploration to run tests in parallel
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/linux/product-build-linux-client.yml
  build/azure-pipelines/product-build-pr.yml
  build/azure-pipelines/win32/product-build-win32.yml
  scripts/test-integration.bat
  scripts/test-integration.sh
  scripts/test-remote-integration.bat
  scripts/test-remote-integration.sh
  scripts/test-web-integration.bat
  scripts/test-web-integration.sh
Labels: engineering

#149426 Handle multiline commit messages when creating PR
  extensions/github/src/pushErrorHandler.ts
Labels: github

#149943 Problems view - add toggle to view problems in a tree/table
  src/vs/base/browser/ui/table/tableWidget.ts
  src/vs/workbench/contrib/markers/browser/constants.ts
  src/vs/workbench/contrib/markers/browser/markers.contribution.ts
  src/vs/workbench/contrib/markers/browser/markers.ts
  src/vs/workbench/contrib/markers/browser/markersModel.ts
  src/vs/workbench/contrib/markers/browser/markersTable.ts
  src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
  src/vs/workbench/contrib/markers/browser/markersView.ts
  src/vs/workbench/contrib/markers/browser/media/markers.css
  src/vs/workbench/contrib/markers/browser/messages.ts
Labels: error-list

#150230 Move out Settings editor indicator label impl
  src/vs/workbench/contrib/preferences/browser/settingsEditor2.ts
  src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts
  src/vs/workbench/contrib/preferences/browser/settingsTree.ts
Labels: debt

#150267 Git - DotGitWatcher should only listed to file changes for the `file` scheme
  extensions/git/src/repository.ts
Labels: git

#150270 SCMInput enablement proposed api
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostSCM.ts
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
  src/vs/workbench/contrib/scm/common/scm.ts
  src/vs/workbench/contrib/scm/common/scmService.ts
  src/vs/workbench/services/extensions/common/extensionsApiProposals.ts
  src/vscode-dts/vscode.proposed.scmInput.d.ts
Labels: git

#150232 Fix default override model value
  src/vs/workbench/contrib/preferences/browser/settingsEditorSettingIndicators.ts
  src/vs/workbench/contrib/preferences/browser/settingsTree.ts
  src/vs/workbench/contrib/preferences/browser/settingsTreeModels.ts
  src/vs/workbench/services/preferences/common/preferences.ts
  src/vs/workbench/services/preferences/common/preferencesModels.ts
Labels: bug, debt

#150297 Git - fix input enablement
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: git

#150308 Move "Configure Display Language" to Action2
  src/vs/workbench/contrib/localizations/browser/localizations.contribution.ts
  src/vs/workbench/contrib/localizations/browser/localizationsActions.ts
Labels: debt, i18n

#150343 Engineering - Refactor cyclic dependency
  src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts
  src/vs/workbench/contrib/markers/browser/constants.ts
  src/vs/workbench/contrib/markers/browser/markers.contribution.ts
  src/vs/workbench/contrib/markers/browser/markers.ts
  src/vs/workbench/contrib/markers/browser/markersTreeViewer.ts
  src/vs/workbench/contrib/markers/browser/markersView.ts
  src/vs/workbench/contrib/markers/browser/markersViewActions.ts
  src/vs/workbench/contrib/markers/common/markers.ts
  src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts
  src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts
Labels: engineering

#95266 A full editor can be used as git commit message editor
  extensions/git/extension.webpack.config.js
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/api/git.d.ts
  extensions/git/src/askpass.ts
  extensions/git/src/commands.ts
  extensions/git/src/git.ts
  extensions/git/src/gitEditor/gitEditor.ts
  extensions/git/src/gitEditor/main.ts
  extensions/git/src/gitEditor/scripts/git-editor-empty.bat
  extensions/git/src/gitEditor/scripts/git-editor-empty.sh
  extensions/git/src/gitEditor/scripts/git-editor.bat
  extensions/git/src/gitEditor/scripts/git-editor.sh
  extensions/git/src/main.ts
  extensions/git/src/repository.ts
  extensions/git/tsconfig.json
  src/vs/workbench/contrib/scm/browser/util.ts
Labels: git

#150487 Revert "A full editor can be used as git commit message editor (#95266)"
  extensions/git/extension.webpack.config.js
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/api/git.d.ts
  extensions/git/src/askpass.ts
  extensions/git/src/commands.ts
  extensions/git/src/git.ts
  extensions/git/src/gitEditor/gitEditor.ts
  extensions/git/src/gitEditor/main.ts
  extensions/git/src/gitEditor/scripts/git-editor-empty.bat
  extensions/git/src/gitEditor/scripts/git-editor-empty.sh
  extensions/git/src/gitEditor/scripts/git-editor.bat
  extensions/git/src/gitEditor/scripts/git-editor.sh
  extensions/git/src/main.ts
  extensions/git/src/repository.ts
  extensions/git/tsconfig.json
  src/vs/workbench/contrib/scm/browser/util.ts
Labels: git

#150547 fix build/npm/preinstall.js node version check
  build/npm/preinstall.js
Labels: triage-needed

#150599 Add onEnterRule for SassDoc documentation
  extensions/scss/language-configuration.json
Labels: css-less-scss

#150715 Warn when using an empty argument
  src/vs/platform/environment/node/argv.ts
  src/vs/platform/environment/node/argvHelper.ts
  src/vs/server/node/server.cli.ts
  src/vs/server/node/server.main.ts
Labels: workbench-cli

#150901 Problems view - fix #150795
  src/vs/workbench/contrib/markers/browser/markersView.ts
Labels: error-list

#150759 Quick spelling update
  extensions/git/src/api/git.d.ts
Labels: triage-needed
