Repository microsoft/vscode, pull requests merged in 2023-03, with the labels that each got.

#176440 only warn when timeout happens
  src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts
Labels: candidate

#127320 ci: switch to core20 for snap
  build/azure-pipelines/linux/snap-build-linux.yml
  build/azure-pipelines/product-build.yml
  resources/linux/snap/electron-launch
  resources/linux/snap/snapcraft.yaml
  src/vs/platform/native/electron-main/nativeHostMainService.ts
Labels: snap

#176633 Changing back the showOrFocusHover to showHover
  src/vs/editor/contrib/hover/browser/hover.ts
Labels: bug, editor-hover

#176150 Screencast ime bug fix(#176331)
  src/vs/workbench/browser/actions/developerActions.ts
Labels: screencast-mode

#171845 Added features and fixes to screencast mode
  src/vs/workbench/browser/actions/developerActions.ts
Labels: screencast-mode

#176688 remove telemetry prop: common.source
  src/vs/code/electron-main/app.ts
  src/vs/code/node/cliProcessMain.ts
  src/vs/code/node/sharedProcess/sharedProcessMain.ts
  src/vs/editor/standalone/browser/standaloneServices.ts
  src/vs/platform/assignment/common/assignmentService.ts
  src/vs/platform/environment/common/environment.ts
  src/vs/platform/environment/common/environmentService.ts
  src/vs/platform/externalServices/common/marketplace.ts
  src/vs/platform/telemetry/common/commonProperties.ts
  src/vs/platform/telemetry/common/serverTelemetryService.ts
  src/vs/platform/telemetry/common/telemetry.ts
  src/vs/platform/telemetry/common/telemetryService.ts
  src/vs/platform/telemetry/common/telemetryUtils.ts
  src/vs/platform/telemetry/node/customEndpointTelemetryService.ts
  src/vs/platform/telemetry/test/browser/telemetryService.test.ts
  src/vs/platform/windows/electron-main/windowImpl.ts
  src/vs/server/node/serverServices.ts
  src/vs/workbench/api/common/extHostTelemetry.ts
  src/vs/workbench/api/test/browser/extHostTelemetry.test.ts
  src/vs/workbench/browser/actions/helpActions.ts
  src/vs/workbench/contrib/debug/common/debugTelemetry.ts
  src/vs/workbench/contrib/performance/browser/startupTimings.ts
  src/vs/workbench/contrib/performance/electron-sandbox/startupTimings.ts
  src/vs/workbench/contrib/search/test/electron-browser/textsearch.perf.integrationTest.ts
  src/vs/workbench/contrib/surveys/browser/ces.contribution.ts
  src/vs/workbench/contrib/surveys/browser/languageSurveys.contribution.ts
  src/vs/workbench/contrib/surveys/browser/nps.contribution.ts
  src/vs/workbench/contrib/tags/electron-sandbox/workspaceTags.ts
  src/vs/workbench/services/assignment/common/assignmentService.ts
  src/vs/workbench/services/extensions/browser/webWorkerExtensionHost.ts
  src/vs/workbench/services/extensions/common/extensionHostProtocol.ts
  src/vs/workbench/services/extensions/common/remoteExtensionHost.ts
  src/vs/workbench/services/extensions/electron-sandbox/localProcessExtensionHost.ts
  src/vs/workbench/services/telemetry/browser/telemetryService.ts
  src/vs/workbench/services/telemetry/browser/workbenchCommonProperties.ts
  src/vs/workbench/services/telemetry/common/workbenchCommonProperties.ts
  src/vs/workbench/services/telemetry/electron-sandbox/telemetryService.ts
  src/vs/workbench/services/telemetry/test/browser/commonProperties.test.ts
  src/vs/workbench/services/telemetry/test/node/commonProperties.test.ts
Labels: telemetry

#176004 Handle `ParameterBindingException` for PowerShell 5.1
  src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1
Labels: triage-needed

#176746 Set className and textContent in the dynamic style element 'monaco-colors' before appended
  src/vs/base/browser/dom.ts
  src/vs/editor/standalone/browser/standaloneThemeService.ts
Labels: triage-needed

#177012 debug: bump js-debug to 1.76.1
  product.json
Labels: candidate

#176952 Git gutter not shown in workspace with multiple folders (#176754)
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: candidate

#176764 fix typos
  build/gulpfile.vscode.web.js
  build/lib/optimize.ts
  extensions/configuration-editing/src/settingsDocumentHelper.ts
  src/vs/platform/configuration/common/configuration.ts
  src/vs/platform/configuration/common/configurationModels.ts
  src/vs/workbench/contrib/extensions/browser/extensionsActions.ts
  src/vs/workbench/services/configuration/browser/configurationService.ts
  src/vs/workbench/services/extensions/common/extensionManifestPropertiesService.ts
Labels: triage-needed

#177654 SCM - fix commit input box selection
  src/vs/workbench/contrib/scm/browser/media/scm.css
Labels: scm

#177813 Making the sticky scroll keep focus when the sticky lines disappear on scrolling
  src/vs/editor/contrib/stickyScroll/browser/stickyScrollController.ts
  src/vs/editor/contrib/stickyScroll/browser/stickyScrollWidget.ts
Labels: bug, verification-needed, editor-sticky-scroll

#177691 Git - fix quick diff edge case when the resource is inside a submodule
  extensions/git/src/repository.ts
Labels: git

#177987 Button - add label getter
  src/vs/base/browser/ui/button/button.ts
Labels: scm

#177859 fix: placing the focus into the editor upon escaping from the content hover
  src/vs/editor/contrib/hover/browser/contentHover.ts
  src/vs/editor/contrib/hover/browser/hover.ts
Labels: bug, editor-hover

#177985 Fix a typo in date.ts
  src/vs/base/common/date.ts
Labels: triage-needed

#177581 Fixes #177580
  build/lib/stylelint/vscode-known-variables.json
  src/vs/workbench/contrib/comments/browser/commentGlyphWidget.ts
  src/vs/workbench/contrib/comments/browser/media/review.css
Labels: triage-needed

#178006 extensions: Make ScrollToTop button less prominent
  src/vs/workbench/contrib/extensions/browser/extensionEditor.ts
Labels: ux

#173305 Allow individual comments to be marked as draft
  src/vs/editor/common/languages.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostComments.ts
  src/vs/workbench/api/common/extHostTypes.ts
  src/vs/workbench/services/extensions/common/extensionsApiProposals.ts
  src/vscode-dts/vscode.proposed.commentsDraftState.d.ts
Labels: api, api-proposal

#178488 Action button - disable button during checkout
  extensions/git/src/actionButton.ts
Labels: git

#178510 debug: bump js-debug
  product.json
Labels: candidate

#178612 Git - remote picker should hide on blur
  extensions/git-base/src/remoteSource.ts
Labels: git

#163190 Add support for multiRange formatting
  src/vs/editor/common/languages.ts
  src/vs/editor/contrib/format/browser/format.ts
  src/vs/monaco.d.ts
  src/vs/workbench/api/browser/mainThreadLanguageFeatures.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostLanguageFeatures.ts
  src/vs/workbench/services/extensions/common/extensionsApiProposals.ts
  src/vscode-dts/vscode.proposed.formatMultipleRanges.d.ts
Labels: feature-request, formatting, api-proposal

#176699 Enable code actions and workspace edits for the scm input
  src/vs/editor/contrib/codeAction/browser/codeActionCommands.ts
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: git
