Repository microsoft/vscode, pull requests merged in 2023-04, with the labels that each got.

#179061 debug: bump js-debug
  product.json
Labels: candidate

#179070 Update JS/TS grammar
  extensions/javascript/syntaxes/JavaScript.tmLanguage.json
  extensions/javascript/syntaxes/JavaScriptReact.tmLanguage.json
  extensions/typescript-basics/cgmanifest.json
  extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json
  extensions/typescript-basics/syntaxes/TypeScriptReact.tmLanguage.json
Labels: candidate

#179183 Git - better validation for the branchProtection setting
  extensions/git/src/repository.ts
Labels: git

#179190 Engineering - update agent pool
  build/azure-pipelines/product-build-pr.yml
Labels: engineering

#179109 fix: glib schema generation for snaps
  resources/linux/snap/electron-launch
  src/vs/platform/native/electron-main/nativeHostMainService.ts
Labels: candidate

#179236 Engineering - fix job name casing
  build/azure-pipelines/product-build.yml
Labels: engineering

#179244 Engineering - update build agents
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/sdl-scan.yml
Labels: engineering

#179581 fix: typos
  extensions/git/src/commands.ts
  src/vs/workbench/browser/parts/compositePart.ts
  src/vs/workbench/browser/parts/panel/panelPart.ts
  src/vs/workbench/browser/parts/sidebar/sidebarPart.ts
  src/vs/workbench/services/editor/common/editorGroupsService.ts
  src/vs/workbench/services/languageDetection/browser/languageDetectionWorkerServiceImpl.ts
Labels: triage-needed

#179617 Pick up TS 5.0.4
  extensions/package.json
  extensions/yarn.lock
Labels: candidate

#179335 [Backport] Fix built-in walkthroughs rendering
  src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts
  src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedService.ts
Labels: candidate

#179752 Git - implement branch protection provider
  extensions/git/src/actionButton.ts
  extensions/git/src/api/git.d.ts
  extensions/git/src/branchProtection.ts
  extensions/git/src/commands.ts
  extensions/git/src/model.ts
  extensions/git/src/repository.ts
  extensions/git/src/statusbar.ts
Labels: git

#179789 GitHub - branch protection provider
  extensions/git/src/api/api1.ts
  extensions/git/src/api/git.d.ts
  extensions/git/src/model.ts
  extensions/git/src/repository.ts
  extensions/github/package.json
  extensions/github/package.nls.json
  extensions/github/src/branchProtection.ts
  extensions/github/src/extension.ts
  extensions/github/src/typings/git.d.ts
Labels: github

#177064 [Monaco] Add `monaco.editor.registerEditorOpener` method to be able to intercept editor open operations
  src/vs/editor/standalone/browser/standaloneEditor.ts
  src/vs/monaco.d.ts
Labels: triage-needed

#171504 SCM - Add `document` property to expose the text document
  extensions/vscode-api-tests/package.json
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostSCM.ts
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
  src/vs/workbench/contrib/scm/common/scm.ts
  src/vs/workbench/services/extensions/common/extensionsApiProposals.ts
  src/vscode-dts/vscode.proposed.scmTextDocument.d.ts
Labels: scm

#180299 SCM - polish scm input validation message layout
  src/vs/workbench/contrib/scm/browser/media/scm.css
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: scm

#180416 GitHub - leveral repository rules for branch protection
  extensions/git/src/api/git.d.ts
  extensions/git/src/branchProtection.ts
  extensions/git/src/repository.ts
  extensions/github/package.nls.json
  extensions/github/src/branchProtection.ts
  extensions/github/src/extension.ts
  extensions/github/src/typings/git.d.ts
Labels: github

#170518 Issue 151220/add current timezone offset variable
  src/vs/editor/contrib/snippet/browser/snippetVariables.ts
  src/vs/editor/contrib/snippet/test/browser/snippetVariables.test.ts
Labels: snippets

#180712 SCM - ActionBar rendering optimization
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: scm

#180975 Add overrideCategory back
  src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedService.ts
Labels: getting-started

#181042 for cached audio cues, reset `currentTime` to 0
  src/vs/platform/audioCues/browser/audioCueService.ts
Labels: candidate

#181040 Revert "Fix: diff editor arrow click enables breakpoint "
  src/vs/editor/browser/widget/diffEditorWidget.ts
  src/vs/editor/browser/widget/inlineDiffMargin.ts
Labels: candidate

#181104 chore: bump distro
  package.json
Labels: candidate

#181137 GitHub - avoid double prompting when github.branchProtection setting is enabled
  extensions/github/src/branchProtection.ts
Labels: github
