Repository microsoft/vscode, pull requests merged in 2023-08, with the labels that each got.

#189335 Fix recently-broken cleanup of obsolete (superseded) extension folders
  src/vs/platform/extensionManagement/node/extensionManagementService.ts
Labels: candidate

#189456 Fix recently-broken cleanup of obsolete (superseded) extension folders
  src/vs/platform/extensionManagement/node/extensionManagementService.ts
Labels: candidate

#189457 Data Loss (stable -> insiders) smoke test fail (fix #189192)
  test/smoke/src/areas/workbench/data-loss.test.ts
Labels: candidate

#189311 Custom context menu runs or selects action under mouse when opened (fix #189167)
  src/vs/base/browser/ui/contextview/contextview.ts
Labels: candidate

#190074 Restore version check (#190042)
  src/vs/platform/extensionManagement/common/extensionsProfileScannerService.ts
Labels: candidate

#187700 cleaning the code, it works now
  build/lib/stylelint/vscode-known-variables.json
  src/vs/base/browser/ui/hover/hover.css
  src/vs/editor/contrib/hover/browser/contentHover.ts
Labels: triage-needed

#184861 adjust tabs and spaces consistent
  extensions/html-language-features/.vscode/settings.json
Labels: triage-needed

#190505 Ensure style element is added to shadowDOM components on colorizeElement
  src/vs/editor/standalone/browser/standaloneEditor.ts
Labels: triage-needed

#191300 Git - fix issue with smart commit and dirty documents
  extensions/git/src/commands.ts
Labels: git

#191054 listWidget: remove redundant logic
  src/vs/base/browser/ui/list/listWidget.ts
Labels: list-widget

#191788 Git - update Explorer welcome view context key
  extensions/git/package.json
Labels: git
