Repository microsoft/vscode, pull requests merged in 2024-10, with the labels that each got.

#230207 Git - fix repository detection when rev-parse returns a UNC path on Windows
  extensions/git/src/git.ts
Labels: git

#230235 SCM - Use the view's contextKeyService when rendering the context menu
  src/vs/workbench/contrib/scm/browser/scmHistoryViewPane.ts
Labels: scm

#230154 Candidate: Avoid breaking wh when model can't be resolved
  src/vs/workbench/api/common/extHostLanguageFeatures.ts
Labels: candidate

#230176 debug: fix escape characters shown when hovering DOM element
  src/vs/workbench/contrib/debug/browser/debugExpressionRenderer.ts
  src/vs/workbench/contrib/debug/browser/debugHover.ts
  src/vs/workbench/contrib/debug/test/browser/baseDebugView.test.ts
Labels: candidate

#230241 SCM - Use view's contextKeyService for the context menu
  src/vs/workbench/contrib/scm/browser/scmHistoryViewPane.ts
Labels: candidate, scm

#230312 Git - better handle conflict during cherry-pick
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/api/git.d.ts
  extensions/git/src/commands.ts
  extensions/git/src/git.ts
  extensions/git/src/repository.ts
Labels: git

#230195 Change Korean font priority
  src/vs/base/browser/ui/contextview/contextview.ts
  src/vs/code/electron-sandbox/processExplorer/media/processExplorer.css
  src/vs/workbench/browser/media/style.css
  src/vs/workbench/contrib/issue/browser/media/issueReporter.css
  src/vs/workbench/contrib/issue/electron-sandbox/media/issueReporter.css
  src/vs/workbench/contrib/issue/electron-sandbox/media/newIssueReporter.css
Labels: triage-needed

#230336 SCM - fix graph color when HEAD is a merge commit
  src/vs/workbench/contrib/scm/browser/scmHistory.ts
Labels: scm

#230389 Git Editor - create document link provider
  extensions/git/src/gitEditor.ts
  extensions/git/src/main.ts
Labels: git

#230238 add esbuild transpiler for fast CI
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/linux/product-build-linux.yml
  build/azure-pipelines/win32/product-build-win32.yml
  build/gulpfile.js
  build/lib/compilation.js
  build/lib/compilation.ts
  build/lib/tsb/index.js
  build/lib/tsb/index.ts
  build/lib/tsb/transpiler.js
  build/lib/tsb/transpiler.ts
  extensions/markdown-language-features/src/test/pasteUrl.test.ts
  package-lock.json
  package.json
Labels: debt

#230508 debug: restore old ANSI behavior for DA's that don't declare support either way
  src/vs/workbench/contrib/debug/browser/debugExpressionRenderer.ts
Labels: candidate

#230352 If account is passed in, treat that as the preference for the call
  src/vs/workbench/api/browser/mainThreadAuthentication.ts
Labels: candidate

#230480 fix: use xz compression when building deb package
  build/azure-pipelines/linux/product-build-linux.yml
  build/gulpfile.vscode.linux.js
Labels: candidate

#230849 Pick up TS 5.6.3
  extensions/package-lock.json
  extensions/package.json
Labels: candidate

#230804 Performance optimization
  src/vs/base/parts/ipc/common/ipc.ts
  src/vs/workbench/services/extensions/common/rpcProtocol.ts
Labels: triage-needed

#232215 fix: assign keybinding for edits view (#232214)
  src/vs/workbench/contrib/chat/browser/actions/chatClearActions.ts
  src/vs/workbench/contrib/chat/browser/actions/chatExecuteActions.ts
  src/vs/workbench/contrib/chat/browser/actions/chatQuickInputActions.ts
  src/vs/workbench/contrib/chat/browser/actions/chatTitleActions.ts
  src/vs/workbench/contrib/chat/browser/chatEditing/chatEditingService.ts
  src/vs/workbench/contrib/chat/browser/chatEditing/chatEditingSession.ts
  src/vs/workbench/contrib/chat/browser/chatWidget.ts
Labels: candidate

#232289 debug: update js-debug 1.95.1 for WASM fix
  product.json
Labels: candidate

#232280 fix: chat panel reopen on workspace trust change
  src/vs/workbench/contrib/chat/browser/actions/chatGettingStarted.ts
Labels: candidate

#232281 Ensure element is not rendered to 0px when updating height async
  src/vs/workbench/contrib/chat/browser/chatListRenderer.ts
Labels: candidate

#232285 fix: Show walkthrough if the extension pack has only 1 walkthrough.
  src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedService.ts
Labels: candidate

#232271 fix: assign better keybinding for edits view on Linux
  src/vs/workbench/contrib/chat/browser/actions/chatClearActions.ts
  src/vs/workbench/contrib/chat/browser/actions/chatQuickInputActions.ts
Labels: candidate

#232302 Remove backcompat workaround
  src/vs/workbench/api/common/extHostTypes.ts
Labels: candidate

#232373 Use async find provider for file scheme only
  src/vs/workbench/contrib/files/browser/views/explorerView.ts
Labels: candidate

#232335 Fix: go grammar update (#232142)
  extensions/go/cgmanifest.json
  extensions/go/syntaxes/go.tmLanguage.json
Labels: triage-needed

#232442 WSL terminal CLI is broken (fix #230584)
  src/vs/server/node/server.cli.ts
Labels: candidate

#232585 SCM - add the ability to hide resource group menus
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: scm

#232587 SCM - add the ability to hide resource actions
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
  src/vs/workbench/contrib/scm/browser/util.ts
Labels: scm

#232318 fix: set args for Retry action in chat editing widget
  src/vs/workbench/contrib/chat/browser/actions/chatTitleActions.ts
  src/vs/workbench/contrib/chat/browser/chatInputPart.ts
Labels: candidate
