Repository microsoft/vscode, pull requests merged in 2024-04, with the labels that each got.

#209022 Fix synchronization of scrolling event flooding
  src/vs/workbench/contrib/scrollLocking/browser/scrollLocking.ts
Labels: candidate

#209327 SCM - Add support for filtering history item changes
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: scm

#209336 fix syncing profiles
  src/vs/platform/userDataSync/common/userDataProfilesManifestSync.ts
Labels: candidate

#209346 SCM - use custom hover for history item statistics
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: scm

#209373 SCM - add history item hover
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: scm

#209419 Engineering - update suppression file
  build/azure-pipelines/config/CredScanSuppressions.json
Labels: engineering

#209819 Git - only add `--ignore-case` if it is a supported flag
  extensions/git/src/git.ts
Labels: git

#209851 Pick up TS 5.4.4
  extensions/package.json
  extensions/yarn.lock
Labels: candidate

#209694 Revert "debug: pass environment via terminal API instead of command (…
  src/vs/workbench/api/node/extHostDebugService.ts
  src/vs/workbench/contrib/debug/node/terminals.ts
Labels: candidate

#209942 Git - add dedicated commands to view changes
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
  src/vs/workbench/browser/parts/editor/editorCommands.ts
  src/vs/workbench/contrib/multiDiffEditor/browser/scmMultiDiffSourceResolver.ts
  src/vs/workbench/contrib/scm/browser/scmViewPane.ts
Labels: git

#210074 Pick up latest TS recovery 5.4.5
  extensions/package.json
  extensions/yarn.lock
Labels: candidate

#210831 Revert "Merge pull request #209136 from cpendery/fix/improve-marker-p…
  src/vs/platform/terminal/common/capabilities/capabilities.ts
  src/vs/platform/terminal/common/capabilities/commandDetection/terminalCommand.ts
  src/vs/platform/terminal/common/capabilities/commandDetectionCapability.ts
  src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts
  src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
  src/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1
Labels: important

#210882 Engineering - update notebooks
  .vscode/notebooks/endgame.github-issues
  .vscode/notebooks/my-endgame.github-issues
Labels: engineering

#211167 Git - fix view untracked changes command visibility
  extensions/git/package.json
Labels: git

#211170 Git - show notification when there are no staged changes/changes/untracked changes
  extensions/git/src/commands.ts
Labels: git

#211524 Fix wrong directory for Custom Editor Labels
  src/vs/workbench/services/editor/common/customEditorLabelService.ts
Labels: candidate

#211499 cli: fix tunnels not working on Windows
  cli/src/tunnels/code_server.rs
Labels: candidate

#211682 Fix workspace symbol search
  extensions/typescript-language-features/src/languageFeatures/workspaceSymbols.ts
Labels: candidate
