Repository microsoft/vscode, pull requests merged in 2025-04, with the labels that each got.

#245235 Revert "chore: pass webviewID with initial version message to sw"
  src/vs/workbench/contrib/webview/browser/pre/index-no-csp.html
  src/vs/workbench/contrib/webview/browser/pre/index.html
  src/vs/workbench/contrib/webview/browser/pre/service-worker.js
Labels: candidate

#245254 Different fix for chat extension welcome views not showing
  src/vs/workbench/contrib/chat/common/chatServiceImpl.ts
Labels: candidate

#245307 Git - fix commit hook setting name
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
Labels: git

#245062 fix: correct filtering logic for file-based recommendations
  src/vs/workbench/contrib/extensions/browser/extensions.contribution.ts
  src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts
Labels: triage-needed

#245331 Engineering - PR pipeline improvements
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/linux/product-build-linux-test.yml
  build/azure-pipelines/linux/product-build-linux.yml
  build/azure-pipelines/product-build-pr.yml
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/win32/product-build-win32-test.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#245293 Register agent mode setting by default on stable
  src/vs/workbench/contrib/chat/browser/chat.contribution.ts
Labels: candidate

#245367 Engineering - run tests based on target
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/linux/product-build-linux-test.yml
  build/azure-pipelines/linux/product-build-linux.yml
  build/azure-pipelines/product-build-pr.yml
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/win32/product-build-win32-test.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#245418 Engineering - update CI build stage names
  build/azure-pipelines/product-build.yml
Labels: engineering

#245425 Engineering - update test timeout for CI build
  build/azure-pipelines/product-build.yml
Labels: engineering

#245460 Engineering - fix check for running browser smoke tests
  build/azure-pipelines/linux/product-build-linux-test.yml
Labels: engineering

#245471 Engineering - revert stage names as the stage names are used for both product build and CI builds
  build/azure-pipelines/product-build.yml
Labels: engineering

#245519 Git - improve git commit diagnostics hook
  extensions/git/src/commands.ts
Labels: git

#245531 Engineering - add macOS coverage to PR pipeline
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/oss/product-build-pr-cache-darwin.yml
  build/azure-pipelines/product-build-pr.yml
Labels: engineering

#242241 Update WinGet configuration file location & extension
  .config/configuration.winget
Labels: triage-needed

#245634 Engineering - bump deemon
  package-lock.json
  package.json
Labels: engineering

#245796 Engineering - background codesign for Windows stage
  build/azure-pipelines/win32/codesign.js
  build/azure-pipelines/win32/codesign.ts
  build/azure-pipelines/win32/product-build-win32.yml
  build/hygiene.js
  build/package-lock.json
  build/package.json
Labels: engineering

#245847 Engineering - update test task display name
  build/azure-pipelines/cli/test.yml
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/linux/product-build-linux-test.yml
  build/azure-pipelines/win32/product-build-win32-test.yml
  build/hygiene.js
Labels: engineering

#245856 Engineering - fix task condition
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#245885 Engineering - background codesign for Windows
  build/azure-pipelines/win32/codesign.js
  build/azure-pipelines/win32/codesign.ts
  build/azure-pipelines/win32/product-build-win32.yml
  build/package-lock.json
  build/package.json
Labels: engineering

#245914 Engineering - refactor codesign script
  build/azure-pipelines/win32/codesign.js
  build/azure-pipelines/win32/codesign.ts
Labels: engineering

#246056 Engineering - bump deemon
  package-lock.json
  package.json
Labels: engineering

#246059 Engineering - refactor macOS stage
  build/azure-pipelines/cli/cli-darwin-sign.yml
  build/azure-pipelines/cli/cli-win32-sign.yml
  build/azure-pipelines/common/checkForArtifact.js
  build/azure-pipelines/common/checkForArtifact.ts
  build/azure-pipelines/common/publish.js
  build/azure-pipelines/common/publish.ts
  build/azure-pipelines/common/waitForArtifacts.js
  build/azure-pipelines/common/waitForArtifacts.ts
  build/azure-pipelines/darwin/codesign.js
  build/azure-pipelines/darwin/codesign.ts
  build/azure-pipelines/darwin/product-build-darwin-sign.yml
  build/azure-pipelines/darwin/product-build-darwin-universal.yml
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/product-build-pr.yml
  build/azure-pipelines/product-build.yml
Labels: engineering

#246219 Git - 💄 adopt `truncate()` in various places
  extensions/git/src/blame.ts
  extensions/git/src/historyProvider.ts
  extensions/git/src/timelineProvider.ts
Labels: git

#246242 Git - add more logging to `provideOriginalResource()`
  extensions/git/src/main.ts
  extensions/git/src/repository.ts
Labels: git

#246285 Engineering - bump deemon
  package-lock.json
  package.json
Labels: engineering

#246295 Git - reduce the number of `getConfiguration()` calls
  extensions/git/src/historyProvider.ts
  extensions/git/src/timelineProvider.ts
  extensions/git/src/util.ts
Labels: git

#225132 A command to accept all combination
  src/vs/workbench/contrib/mergeEditor/browser/commands/commands.ts
  src/vs/workbench/contrib/mergeEditor/browser/mergeEditor.contribution.ts
Labels: feature-request, merge-editor

#246339 Engineering - bump deemon
  package-lock.json
  package.json
Labels: engineering

#246344 Engineering - linux codesign in the background
  build/azure-pipelines/linux/codesign.js
  build/azure-pipelines/linux/codesign.ts
  build/azure-pipelines/linux/product-build-linux.yml
Labels: engineering

#246468 Engineering - move CLI jobs back to hosted pool
  build/azure-pipelines/product-build.yml
Labels: engineering

#246536 Engineering - bump deemon
  package-lock.json
  package.json
Labels: engineering

#246537 Git - fix git blame status bar item
  extensions/git/src/blame.ts
Labels: git

#246494 Update chatExecuteActions.ts
  src/vs/workbench/contrib/chat/browser/actions/chatExecuteActions.ts
Labels: triage-needed

#246604 SCM - 💄 fix off by one error
  src/vs/workbench/contrib/scm/browser/quickDiffWidget.ts
Labels: scm

#246621 Engineering - Revert "Bump @octokit/endpoint, @octokit/graphql and @octokit/rest in /extensions/github (#240838)"
  extensions/github/package-lock.json
  extensions/github/package.json
Labels: github

#246707 SCM - add secondary quick diff provider
  build/lib/stylelint/vscode-known-variables.json
  extensions/git/package.json
  extensions/git/package.nls.json
  extensions/git/src/commands.ts
  extensions/git/src/main.ts
  extensions/git/src/repository.ts
  extensions/git/src/staging.ts
  src/vs/workbench/api/browser/mainThreadEditors.ts
  src/vs/workbench/api/browser/mainThreadQuickDiff.ts
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostSCM.ts
  src/vs/workbench/contrib/scm/browser/media/dirtydiffDecorator.css
  src/vs/workbench/contrib/scm/browser/quickDiffDecorator.ts
  src/vs/workbench/contrib/scm/browser/quickDiffModel.ts
  src/vs/workbench/contrib/scm/browser/quickDiffWidget.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
  src/vscode-dts/vscode.proposed.quickDiffProvider.d.ts
Labels: scm

#246711 SCM - 💄 cleanup `isSCM` property from quick diff providers
  src/vs/workbench/api/browser/mainThreadQuickDiff.ts
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#246716 Revert "SCM - 💄 cleanup `isSCM` property from quick diff providers (#246711)"
  src/vs/workbench/api/browser/mainThreadQuickDiff.ts
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#246754 SCM - second attemt to clean up `isSCM`
  src/vs/workbench/api/browser/mainThreadQuickDiff.ts
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#246756 SCM - tweak secondary decoration color and pattern
  src/vs/workbench/contrib/scm/browser/media/dirtydiffDecorator.css
  src/vs/workbench/contrib/scm/common/quickDiff.ts
Labels: scm

#247071 SCM - add visibility toggle to context menu
  src/vs/platform/actions/common/actions.ts
  src/vs/workbench/contrib/scm/browser/quickDiffDecorator.ts
  src/vs/workbench/contrib/scm/browser/quickDiffModel.ts
  src/vs/workbench/contrib/scm/browser/scm.contribution.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#247073 SCM - tweak secondary diff decoration colors
  src/vs/workbench/contrib/scm/common/quickDiff.ts
Labels: scm

#247103 SCM - 💄 remove `visible` property from quickDiffProvider API proposal
  src/vs/workbench/api/browser/mainThreadQuickDiff.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostQuickDiff.ts
  src/vscode-dts/vscode.proposed.quickDiffProvider.d.ts
Labels: scm

#247129 SCM - maintain quick diff provider visibility
  src/vs/workbench/api/browser/mainThreadQuickDiff.ts
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostQuickDiff.ts
  src/vs/workbench/contrib/scm/browser/quickDiffDecorator.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
  src/vscode-dts/vscode.proposed.quickDiffProvider.d.ts
Labels: scm

#247154 Engineering - update endgame notebooks
  .vscode/notebooks/endgame.github-issues
  .vscode/notebooks/my-endgame.github-issues
Labels: engineering

#247161 SCM - fix issue related to deleted line decoration
  src/vs/workbench/contrib/scm/browser/media/dirtydiffDecorator.css
Labels: scm

#247198 SCM - 💄 quick diff service cleanup
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#247205 SCM - more quick diff cleanup
  src/vs/workbench/api/common/extHostQuickDiff.ts
  src/vs/workbench/contrib/scm/browser/quickDiffModel.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
Labels: scm

#247219 SCM - more quick diff code cleanup
  src/vs/workbench/contrib/scm/browser/quickDiffDecorator.ts
  src/vs/workbench/contrib/scm/browser/quickDiffModel.ts
  src/vs/workbench/contrib/scm/browser/quickDiffWidget.ts
  src/vs/workbench/contrib/scm/common/quickDiff.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#245779 Replace single line break with double line break for commit description in git blame hover popup
  extensions/git/src/blame.ts
  src/vs/workbench/contrib/scm/browser/scmHistoryViewPane.ts
Labels: git

#247322 GitHub - revert ESM migration
  build/lib/extensions.js
  build/lib/extensions.ts
  extensions/github/extension.webpack.config.js
  extensions/github/package-lock.json
  extensions/github/package.json
  extensions/github/src/auth.ts
  extensions/github/src/branchProtection.ts
  extensions/github/src/canonicalUriProvider.ts
  extensions/github/src/commands.ts
  extensions/github/src/credentialProvider.ts
  extensions/github/src/extension.ts
  extensions/github/src/historyItemDetailsProvider.ts
  extensions/github/src/links.ts
  extensions/github/src/publish.ts
  extensions/github/src/pushErrorHandler.ts
  extensions/github/src/remoteSourceProvider.ts
  extensions/github/src/remoteSourcePublisher.ts
  extensions/github/src/shareProviders.ts
  extensions/github/src/test/github.test.ts
  extensions/github/src/test/index.ts
  extensions/github/src/util.ts
  extensions/github/tsconfig.json
Labels: github

#247311 ensure publish script checks for stage success at the end
  build/azure-pipelines/common/publish.js
  build/azure-pipelines/common/publish.ts
  build/azure-pipelines/product-publish.yml
Labels: engineering

#247264 fix: toggleApplicationScope typo
  src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts
  src/vs/platform/extensionManagement/common/extensionManagement.ts
  src/vs/platform/extensionManagement/common/extensionManagementIpc.ts
  src/vs/workbench/contrib/extensions/browser/extensionsWorkbenchService.ts
  src/vs/workbench/contrib/userDataProfile/browser/userDataProfilesEditorModel.ts
  src/vs/workbench/services/extensionManagement/common/extensionManagementChannelClient.ts
  src/vs/workbench/services/extensionManagement/common/extensionManagementService.ts
  src/vs/workbench/test/browser/workbenchTestServices.ts
Labels: triage-needed

#247379 Engineering - OSS tool result
  ThirdPartyNotices.txt
  cli/ThirdPartyNotices.txt
Labels: engineering

#247383 SCM - only show submenu when diff decorations appear in the editor gutter
  src/vs/workbench/contrib/scm/browser/scm.contribution.ts
Labels: scm

#247384 SCM - remove temporary fix for repository codicon alignment
  src/vs/workbench/contrib/scm/browser/activity.ts
  src/vs/workbench/contrib/scm/browser/media/scm.css
Labels: scm

#247588 SCM - fix quick diff provider in multi-repository workspace
  src/vs/workbench/contrib/scm/browser/quickDiffDecorator.ts
  src/vs/workbench/contrib/scm/common/quickDiffService.ts
Labels: scm

#247717 Git - quick diff decoration label casing
  extensions/git/src/repository.ts
Labels: git

#247680 UI and image fixes for new walkthrough
  src/vs/workbench/contrib/welcomeGettingStarted/browser/media/gettingStarted.css
  src/vs/workbench/contrib/welcomeGettingStarted/common/media/multi-file-edits.svg
Labels: ux

#247770 Git - fix unstage selected ranges command
  extensions/git/src/commands.ts
Labels: git

#210875 fixes issue #662 (enables Pointer Lock Web API)
  src/vs/code/electron-main/app.ts
Labels: postponed-during-endgame

#247762 add gitPullRequestDone icon to codiconsLibrary
  src/vs/base/browser/ui/codicons/codicon/codicon.ttf
  src/vs/base/common/codiconsLibrary.ts
Labels: icons-product

#247848 Git - fallback to `relative()` when computing relative paths
  extensions/git/src/git.ts
Labels: git

#247853 Git - add support for unstaging a subset of lines
  extensions/git/src/commands.ts
  extensions/git/src/staging.ts
Labels: git
