Repository microsoft/vscode, pull requests merged in 2025-09, with the labels that each got.

#264162 docs: fix grammar in Development Container section
  README.md
Labels: triage-needed

#264884 Chat - set minimum fontSize to 6
  src/vs/workbench/contrib/chat/browser/chat.contribution.ts
Labels: panel-chat

#264896 Chat - more font family/size fixes
  src/vs/workbench/contrib/chat/browser/media/chat.css
  src/vs/workbench/contrib/chat/browser/media/chatCodeBlockPill.css
Labels: panel-chat

#264924 Chat - fix progress indicator in Ask mode
  src/vs/workbench/contrib/chat/browser/media/chat.css
Labels: panel-chat

#264803 remove `id` property from ChatSessionsContribution
  src/vs/workbench/contrib/chat/browser/chatSessions.contribution.ts
  src/vs/workbench/contrib/chat/common/chatSessionsService.ts
Labels: debt

#265007 fix: memory leak in QuickDiffModel
  src/vs/workbench/contrib/scm/browser/quickDiffModel.ts
Labels: triage-needed

#265158 Chat - fix chat layout in floating window
  build/lib/stylelint/vscode-known-variables.json
  src/vs/workbench/contrib/chat/browser/chatLayoutService.ts
  src/vs/workbench/contrib/chat/browser/chatWidget.ts
  src/vs/workbench/contrib/chat/browser/media/chat.css
  src/vs/workbench/contrib/chat/common/chatLayoutService.ts
  src/vs/workbench/contrib/inlineChat/test/browser/inlineChatController.test.ts
Labels: panel-chat

#265319 Fire event on assignment context updates
  src/vs/workbench/services/assignment/common/assignmentService.ts
Labels: candidate

#265425 Fix smoke tests in release branch
  src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts
  src/vs/workbench/services/dialogs/common/dialogService.ts
  test/automation/src/quickaccess.ts
Labels: candidate

#265822 Chat - add support for selection when attaching a file
  src/vs/workbench/contrib/chat/browser/actions/chatActions.ts
Labels: chat

#265751 match orgs from chat extension
  src/vs/workbench/contrib/chat/common/chatEntitlementService.ts
  src/vs/workbench/services/assignment/common/assignmentFilters.ts
Labels: candidate

#265786 Small fix to chat sessions sentiment check
  src/vs/workbench/contrib/chat/browser/chatSessions.ts
Labels: candidate

#265844 SCM - add method to resolve a source control history item
  extensions/git/src/historyProvider.ts
  src/vs/workbench/api/browser/mainThreadSCM.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostSCM.ts
  src/vs/workbench/contrib/scm/common/history.ts
  src/vscode-dts/vscode.proposed.scmHistoryProvider.d.ts
Labels: scm

#265855 Chat - add the option to programatically attach a history item change
  src/vs/workbench/contrib/chat/browser/actions/chatActions.ts
Labels: chat

#266337 Chat: telemetry for `alreadyInstalled` chat install kind missing and provider is wrong (#266334)
  src/vs/workbench/contrib/chat/browser/chatSetup.ts
Labels: candidate

#266239 Fix TOC in release notes
  src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
Labels: candidate

#267112 Git - path comparison should better handle trailing/mixed separators
  extensions/git/src/util.ts
Labels: git

#267389 Engineering - update distro
  package.json
Labels: engineering

#267741 Engineering - fix publish stage
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/product-publish.yml
Labels: engineering

#263228 Fix a typo in nls.localize(...) in localization.contribution.ts
  src/vs/workbench/contrib/localization/common/localization.contribution.ts
Labels: triage-needed

#268110 Engineering - move Windows CLI job into the template
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/win32/product-build-win32-cli-sign.yml
Labels: engineering

#268131 Engineering - extract Windows ci jobs in a template
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/win32/product-build-win32-ci.yml
  build/azure-pipelines/win32/product-build-win32-test.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#268167 Engineering - move jobs into templates
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/product-compile.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#268171 Engineering - fix Windows stage
  build/azure-pipelines/win32/product-build-win32-ci.yml
  build/azure-pipelines/win32/product-build-win32-compile.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#267167 Removed 'add context...' from chat input button label
  src/vs/workbench/contrib/chat/browser/chatInputPart.ts
  src/vs/workbench/contrib/chat/browser/media/chat.css
Labels: ux

#268182 Add `toolMetadata` support to Language Model Tool Results
  src/vs/workbench/api/browser/mainThreadLanguageModelTools.ts
  src/vs/workbench/api/common/extHostTypeConverters.ts
  src/vs/workbench/api/common/extHostTypes.ts
  src/vs/workbench/contrib/chat/common/languageModelToolsService.ts
  src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/tools/runInTerminalTool.ts
  src/vscode-dts/vscode.proposed.chatParticipantPrivate.d.ts
Labels: triage-needed

#268267 Engineering - cleanup Windows CLI jobs
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/win32/product-build-win32-ci.yml
  build/azure-pipelines/win32/product-build-win32-cli-compile.yml
  build/azure-pipelines/win32/product-build-win32-cli-sign.yml
  build/azure-pipelines/win32/product-build-win32-cli.yml
  build/azure-pipelines/win32/product-build-win32.yml
  build/azure-pipelines/win32/steps/product-build-win32-cli-sign.yml
  build/azure-pipelines/win32/steps/product-build-win32-compile.yml
  build/azure-pipelines/win32/steps/product-build-win32-install-rust.yml
  build/azure-pipelines/win32/steps/product-build-win32-test.yml
Labels: engineering

#268295 Engineering - use Terrapin for CI builds
  build/azure-pipelines/product-build.yml
Labels: engineering

#268080 Empty state chat history 2.0
  src/vs/platform/actions/common/actions.ts
  src/vs/workbench/contrib/chat/browser/actions/chatActions.ts
  src/vs/workbench/contrib/chat/browser/chat.ts
  src/vs/workbench/contrib/chat/browser/chatWidget.ts
  src/vs/workbench/contrib/chat/browser/media/chatViewWelcome.css
  src/vs/workbench/contrib/chat/browser/viewsWelcome/chatViewWelcomeController.ts
Labels: ux, chat

#268828 Engineering - refactor Linux stage
  build/azure-pipelines/linux/codesign.js
  build/azure-pipelines/linux/codesign.ts
  build/azure-pipelines/linux/product-build-linux-ci.yml
  build/azure-pipelines/linux/product-build-linux.yml
  build/azure-pipelines/linux/steps/product-build-linux-compile.yml
  build/azure-pipelines/linux/steps/product-build-linux-test.yml
  build/azure-pipelines/product-build.yml
Labels: engineering

#268839 Engineering - add node_modules stage to keep node_modules cache warm
  build/azure-pipelines/alpine/product-build-alpine-node-modules.yml
  build/azure-pipelines/darwin/product-build-darwin-node-modules.yml
  build/azure-pipelines/linux/product-build-linux-node-modules.yml
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/web/product-build-web-node-modules.yml
  build/azure-pipelines/win32/product-build-win32-node-modules.yml
Labels: engineering

#268847 Engineering - remove task that is not needed
  build/azure-pipelines/win32/product-build-win32-node-modules.yml
  build/azure-pipelines/win32/steps/product-build-win32-compile.yml
Labels: engineering

#268870 Engineering - set isProduction for artifacts
  build/azure-pipelines/common/publish-artifact.yml
Labels: engineering

#269105 Improve status bar item hover colors for accessibility
  extensions/theme-defaults/themes/dark_modern.json
  extensions/theme-defaults/themes/light_modern.json
  src/vs/workbench/browser/parts/statusbar/media/statusbarpart.css
  src/vs/workbench/common/theme.ts
Labels: ux, papercut :drop_of_blood:

#268998 suggested prompt style and reposition
  src/vs/workbench/contrib/chat/browser/media/chatViewWelcome.css
  src/vs/workbench/contrib/chat/browser/viewsWelcome/chatViewWelcomeController.ts
Labels: ux, chat
