Repository microsoft/vscode, pull requests merged in 2025-06, with the labels that each got.

#250289 Engineering - bump version
  package-lock.json
  package.json
Labels: engineering

#250556 GitHub - fix auth regression
  extensions/github/src/auth.ts
Labels: github

#250531 Chat code block pill token updates
  build/lib/stylelint/vscode-known-variables.json
  src/vs/base/browser/ui/iconLabel/iconlabel.css
  src/vs/workbench/contrib/chat/browser/media/chatCodeBlockPill.css
  src/vs/workbench/contrib/chat/common/chatColors.ts
Labels: ux, accessibility

#250779 Improve debug adapter capabilities checking
  src/vs/workbench/contrib/debug/browser/debug.contribution.ts
  src/vs/workbench/contrib/debug/common/debug.ts
  src/vs/workbench/contrib/debug/common/debugViewModel.ts
Labels: triage-needed

#251059 fix: revert to NSAccessibilityStaticTextRole for list elements
  .npmrc
  package.json
Labels: candidate

#233733 Allow unregistering registerSchemaContribution
  src/vs/editor/standalone/browser/standaloneServices.ts
  src/vs/platform/keybinding/common/abstractKeybindingService.ts
  src/vs/platform/keybinding/common/keybinding.ts
  src/vs/platform/keybinding/test/common/abstractKeybindingService.test.ts
  src/vs/platform/keybinding/test/common/mockKeybindingService.ts
  src/vs/workbench/services/keybinding/browser/keybindingService.ts
Labels: postponed-during-endgame

#251151 chat: move extension tools out of preview
  src/vs/workbench/contrib/chat/browser/chat.contribution.ts
Labels: candidate

#251114 Consolidate ps1 shell integration vars into __VSCodeState
  src/vs/workbench/contrib/terminal/common/scripts/shellIntegration.ps1
Labels: bug, terminal-shell-pwsh

#251266 GitHub - cleanup octokit auth
  extensions/github/src/auth.ts
  extensions/github/src/branchProtection.ts
  extensions/github/src/extension.ts
  extensions/github/src/historyItemDetailsProvider.ts
Labels: github

#251272 update `sync` and `sync-ignored` icons
  src/vs/base/browser/ui/codicons/codicon/codicon.ttf
Labels: icons-product

#232768 fix: try always rendering scrollbar in chat editing file list
  src/vs/workbench/contrib/chat/browser/chatContentParts/chatReferencesContentPart.ts
  src/vs/workbench/contrib/chat/browser/chatInputPart.ts
  src/vs/workbench/contrib/chat/browser/chatListRenderer.ts
Labels: postponed-during-endgame

#251374 Git - fix race condition with computing teh branch base
  extensions/git/src/git.ts
  extensions/git/src/historyProvider.ts
  extensions/git/src/repository.ts
Labels: git

#251799 fix: web detection for typescript language server
  extensions/typescript-language-features/src/utils/platform.ts
Labels: candidate

#251755 Restarting task should read the updated content
  src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts
  src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts
  src/vs/workbench/contrib/tasks/common/taskSystem.ts
Labels: bug, tasks

#252202 Fix typo (an language model call → a language model call)
  src/vs/workbench/contrib/mcp/common/mcpSamplingService.ts
Labels: triage-needed

#252791 SCM - refactor Repositories view
  src/vs/workbench/contrib/scm/browser/media/scm.css
  src/vs/workbench/contrib/scm/browser/scmRepositoriesViewPane.ts
Labels: scm
