Repository microsoft/vscode, pull requests merged in 2025-08, with the labels that each got.

#259081 Allow the canonical package name and version to be sent back from the install flow
  src/vs/workbench/contrib/mcp/browser/mcpCommandsAddConfiguration.ts
Labels: triage-needed

#259238 add backticks vs single quotes around task labels for result messages
  src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/createAndRunTaskTool.ts
  src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/getTaskOutputTool.ts
  src/vs/workbench/contrib/terminalContrib/chatAgentTools/browser/task/runTaskTool.ts
Labels: candidate

#257271 Add the ability to clear a ChatResponseStream, passing in a reason which results in a warning being displayed
  src/vs/workbench/api/common/extHost.api.impl.ts
  src/vs/workbench/api/common/extHost.protocol.ts
  src/vs/workbench/api/common/extHostChatAgents2.ts
  src/vs/workbench/api/common/extHostTypes.ts
  src/vs/workbench/contrib/chat/common/chatModel.ts
  src/vs/workbench/contrib/chat/common/chatService.ts
  src/vscode-dts/vscode.proposed.chatParticipantAdditions.d.ts
Labels: candidate

#259644 Wait for chat session contribution registration
  src/vs/workbench/contrib/chat/browser/chatEditor.ts
  src/vs/workbench/contrib/chat/browser/chatSessions.contribution.ts
  src/vs/workbench/contrib/chat/test/browser/chatEditingService.test.ts
  src/vs/workbench/contrib/inlineChat/test/browser/inlineChatSession.test.ts
Labels: candidate

#259595 Promote terminal auto approve to GA
  src/vs/workbench/contrib/terminalContrib/chatAgentTools/common/terminalChatAgentToolsConfiguration.ts
Labels: candidate

#259333 Restore alt+left/right keybinding to switch terminal pane
  src/vs/workbench/contrib/terminal/browser/terminalActions.ts
  src/vs/workbench/contrib/terminal/browser/terminalGroupService.ts
  src/vs/workbench/contrib/terminal/browser/terminalMenus.ts
  src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts
  src/vs/workbench/contrib/terminal/common/terminalContextKey.ts
  src/vs/workbench/contrib/terminalContrib/sendSequence/browser/terminal.sendSequence.contribution.ts
Labels: candidate

#259661 reverted 'Generate Code' to 'Copilot'
  src/vs/workbench/contrib/chat/browser/actions/chatActions.ts
Labels: candidate

#259805 Git - Revert "fix command not found issues (#256479)"
  src/vs/workbench/api/common/extHostSCM.ts
Labels: git

#259890 Add experiment flag to todo list setting
  src/vs/workbench/contrib/chat/browser/chat.contribution.ts
  src/vs/workbench/contrib/chat/common/tools/manageTodoListTool.ts
Labels: candidate

#259897 Ensure old terminal toolSpecificData format is supported
  src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolSubPart.ts
Labels: candidate

#259881 updated release notes rendering to support new format
  src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts
Labels: candidate

#261003 fix: restore old style context menu on windows for stable
  build/win32/code.iss
Labels: candidate

#260430 Use the tenantId property instead
  extensions/microsoft-authentication/src/node/authProvider.ts
Labels: candidate

#261100 Ensure a reference to model is kept for terminal confirmation
  src/vs/workbench/contrib/chat/browser/chatContentParts/toolInvocationParts/chatTerminalToolSubPart.ts
Labels: candidate

#261565 Revert "TerminalTaskSystem: Fix addtion arguments for string command …
  src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts
Labels: regression

#262276 Engineering - cleanup pull request ADO pipeline
  build/azure-pipelines/alpine/cli-build-alpine.yml
  build/azure-pipelines/cli/cli-compile.yml
  build/azure-pipelines/cli/test.yml
  build/azure-pipelines/darwin/cli-build-darwin.yml
  build/azure-pipelines/darwin/product-build-darwin-cli-sign.yml
  build/azure-pipelines/darwin/product-build-darwin-test.yml
  build/azure-pipelines/darwin/product-build-darwin.yml
  build/azure-pipelines/linux/cli-build-linux.yml
  build/azure-pipelines/linux/product-build-linux-test.yml
  build/azure-pipelines/linux/product-build-linux.yml
  build/azure-pipelines/oss/product-build-pr-cache-darwin.yml
  build/azure-pipelines/oss/product-build-pr-cache-linux.yml
  build/azure-pipelines/oss/product-build-pr-cache-win32.yml
  build/azure-pipelines/product-build-macos.yml
  build/azure-pipelines/product-build-pr.yml
  build/azure-pipelines/product-build.yml
  build/azure-pipelines/product-compile.yml
  build/azure-pipelines/win32/cli-build-win32.yml
  build/azure-pipelines/win32/product-build-win32-cli-sign.yml
  build/azure-pipelines/win32/product-build-win32-test.yml
  build/azure-pipelines/win32/product-build-win32.yml
Labels: engineering

#262292 SCM - reset pinned repository if the pinned repository was removed
  src/vs/workbench/contrib/scm/browser/scmViewService.ts
Labels: scm

#262458 Git - reveal specific file in the multi-file diff editor
  extensions/git/src/blame.ts
  extensions/git/src/commands.ts
  extensions/git/src/timelineProvider.ts
Labels: git

#262420 support model switching in automation
  src/vs/workbench/contrib/chat/browser/actions/chatActions.ts
  src/vs/workbench/contrib/chat/browser/chatInputPart.ts
Labels: triage-needed

#263284 SCM - fix regression for showing the provider type
  src/vs/workbench/contrib/scm/browser/media/scm.css
Labels: scm

#263147 fix: memory leak in accessibilty signal scheduler
  src/vs/platform/accessibilitySignal/browser/progressAccessibilitySignalScheduler.ts
Labels: triage-needed

#263455 Chat - adopt fontSize setting for UI elements
  build/lib/stylelint/vscode-known-variables.json
  src/vs/workbench/contrib/chat/browser/chatWidget.ts
  src/vs/workbench/contrib/chat/browser/media/chat.css
Labels: chat

#263507 `workbench.action.chat.export` optionally accept path
  src/vs/workbench/contrib/chat/browser/actions/chatImportExport.ts
Labels: triage-needed

#263833 Chat - extract font configuration into a separate service
  src/vs/workbench/contrib/chat/browser/chat.contribution.ts
  src/vs/workbench/contrib/chat/browser/chatLayoutService.ts
  src/vs/workbench/contrib/chat/browser/chatWidget.ts
  src/vs/workbench/contrib/chat/common/chatLayoutService.ts
  src/vs/workbench/contrib/inlineChat/test/browser/inlineChatController.test.ts
Labels: chat

#263847 Chat - scale the todo list when fontSize is increased
  src/vs/workbench/contrib/chat/browser/media/chat.css
Labels: chat

#264047 Revert "fix: confirm response based on promise (#263894)"
  src/vs/workbench/contrib/chat/common/chatProgressTypes/chatToolInvocation.ts
Labels: triage-needed
